### ISSUE TITLE
How to get a list from Memberof attribute?

### ISSUE THREAD

**Issue by emailtowalter** [dsbenghe/Novell.Directory.Ldap.NETStandard#1]
Not neccessary a issue, but want to ask: memberof have a list of groups that the member belongs to. How to get a list? I used the following logic , but only get the first one. 

Thanks,

LdapAttribute attribute = (LdapAttribute)ienum.Current;
                    string attributeName = attribute.Name;
                    string attributeVal = attribute.StringValue;
                    if (!Base64.isLDIFSafe(attributeVal))
                    {
                        byte[] tbyte = SupportClass.ToByteArray(attributeVal);
                        attributeVal = Base64.encode(SupportClass.ToSByteArray(tbyte));
                    }

**Comment by dsbenghe** [comment]
attribute.StringValues looks to contain what are you looking for.

**Comment by emailtowalter** [comment]
It worked! Thanks !

**Comment by aniljain100** [comment]
Hello,

Apologies to invoke this thread. At the first place I am unable to add MemberOf attribute to the user. Its throwing me Ldaperrormessage:

"0000209A: SvcErr: DSID-031A1081, problem 5003 (WILL_NOT_PERFORM), data 0\n\0"

Here is my code:
```
LdapAttributeSet attributeSet = new LdapAttributeSet();
attributeSet.Add(new LdapAttribute("objectclass", "inetOrgPerson"));
attributeSet.Add(new LdapAttribute("MemberOf",
  new string[] { "CN=Group name,CN=Users,DC=domain name,DC=local" }));
attributeSet.Add(new LdapAttribute("givenname",
       "Anilsnew1"));
attributeSet.Add(new LdapAttribute("sn", "Anilsnew1"));
attributeSet.Add(new LdapAttribute("telephonenumber", "1 801 555 1212"));
attributeSet.Add(new LdapAttribute("mail", "anilsnew1@own.com"));
//attributeSet.Add(new LdapAttribute("userpassword", "Anilsnew"));

string dn = "cn=Anilsnew1," + containerName;
LdapEntry newEntry = new LdapEntry(dn, attributeSet);
LdapConnection conn = new LdapConnection();
Console.WriteLine("Connecting to:" + ldapHost);
conn.Connect(ldapHost, ldapPort);
conn.Bind(loginDN, password);
conn.Add(newEntry);
Console.WriteLine("Entry:" + dn + "  Added Successfully");
```

Any idea what's wrong?

Thanks
Anil Jain

**Comment by dsbenghe** [comment]
See my answer to your original issue - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/21

**Comment by aniljain100** [comment]
Hi,

Thanks. It worked for me as well.
