### ISSUE TITLE
Interface "ILdapConnection" is missing a method

### ISSUE THREAD

**Issue by matteo-mosca** [dsbenghe/Novell.Directory.Ldap.NETStandard#10]
The interface "ILdapConnection" is missing the "Disconnect" method signature, which is present on the default implementation "LdapConnection".

This issue is preventing us from declaring the interface as a dependency instead of the implementation, with all the obvious problems (cannot inject, cannot unit test).

Other methods might be missing, I noticed this one since we are using it.

**Comment by dsbenghe** [comment]
I merged your pull request 2 days ago and published new version.
