### ISSUE TITLE
Hang on Disconnect when using StartTls and not StopTls before Disconnect

### ISSUE THREAD

**Issue by Kim-SSi** [dsbenghe/Novell.Directory.Ldap.NETStandard#101]
I have traced a hang in my app on ldap disconnect to:
https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/e4f2934d1d8e2e56576458d05e656e212040ba90/src/Novell.Directory.Ldap.NETStandard/Connection.cs#L1142

I am unsure if it is related to updating to .NET 4.8.
I only occurs when using StartTls and not using StopTls before disconnecting.

Reproducer code:

```
public void HangReproducerPlainOk()
{
	using (var cn = new LdapConnection())
	{
		cn.UserDefinedServerCertValidationDelegate += CnOnUserDefinedServerCertValidationDelegate; //Bypass any cert problems
		// connect
		cn.Connect("192.168.123.217", 389);
		cn.Disconnect();
	}
}

public void HangReproducerIssue()
{
	using (var cn = new LdapConnection())
	{
		cn.UserDefinedServerCertValidationDelegate += CnOnUserDefinedServerCertValidationDelegate; //Bypass any cert problems
		// connect
		cn.Connect("192.168.123.217", 389);
		cn.StartTls();
		cn.Disconnect(); //Hangs here
	}
}

public void HangReproducerTlsOkIfStopped()
{
	using (var cn = new LdapConnection())
	{
		cn.UserDefinedServerCertValidationDelegate += CnOnUserDefinedServerCertValidationDelegate; //Bypass any cert problems
		// connect
		cn.Connect("192.168.123.217", 389);
		cn.StartTls();
		cn.StopTls();
		cn.Disconnect();
	}
}

private bool CnOnUserDefinedServerCertValidationDelegate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslpolicyerrors)
{
	return true;
}
```
The server that I am connecting to is running Samba4. I am running an instance of:
https://www.turnkeylinux.org/domain-controller
It is setup using the default settings with 3 additional accounts and 2 groups.
If I can help with any other information please let me know.

**Comment by Kim-SSi** [comment]
My workaround is to call a StopTls if connection.Tls before Disconnect and change the line as it is a background thread to:
```
_enclosedThread.Join(1000);
```

**Comment by CDoughty08** [comment]
This is still an issue with 3.6.0 and 4.0.0-beta3 with .Net 6

OS: RHEL 8 and RHEL 7
