### ISSUE TITLE
Getting Universal Password

### ISSUE THREAD

**Issue by Vorobjov** [dsbenghe/Novell.Directory.Ldap.NETStandard#107]
Hello! 
First of all thanks for this project, its highly useful! 
Novell supports such feature as universal password which allows getting users password in plain text via code. This feature is implemented in FreeRADIUS project has it fully implemented for C language and their implementation can be found here: https://github.com/FreeRADIUS/freeradius-server/blob/master/src/lib/ldap/edir.c . So the question is does this project support getting universal password in similar or any other way?

**Comment by ASokolovics** [comment]
I created github account only to contribute to this issue. I have similar problem as OP, I'm trying to programmatically get universal password using c#, so far the only thing that I managed to get work is "getpass" linux application https://github.com/tjpatter/getpass . This is C based console application that is using some precompiled lib files to extract universal password in plain text.
LDAP Wiki has posted that they made some kind of c# framework that uses precompiled C DLLs ( https://github.com/jwilleke/identity-projects/tree/master/dotnet ), but the problem with this one, they use DLLs from 2009 and I dont think that they will work with OES 2018 on the backend or even Windows 10 on the frontend, anyways I tried everything and was not able to make it work. 
Then I found this solution and and started reading the code and realised that all ber encryption/decryption, handling of ldap extended operations etc. is already present in this solution and from my undestanding, the only thing I need to do is add one more extended operation for universal password retrieval. As an example of how to do it I looked at WhoAmI extended operation added by the author of this project. Am I on the right way to get it done or am I missing something ? My plan was to port freeRADIUS C solution mentioned by OP to c# using the framework of this project.
