### ISSUE TITLE
Incorrect timeout when using SSL

### ISSUE THREAD

**Issue by DostojnyKocur** [dsbenghe/Novell.Directory.Ldap.NETStandard#110]
When trying to connect to an inaccessible LDAP instance through SSL then connection is failed only after 21 seconds regardless of set connection timeout.

We use the library like below:
```
var connection = new LdapConnection
{
    SecureSocketLayer = true,
    ConnectionTimeout = 5000
};
connection.Connect(hostName, 636);
connection.Bind(login, password);
```

Currently correct timeout is used only when an LDAP instance can be pinged. 

I checked it and found out that in case of connection through SSL there is used Socket.Connect() which does not have set timeout. As a solution asynchronous Socket.BeginConnect() can be used along with set Socket.SendTimeout. When ordinary TCP connection is used then timeout works well.

https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/master/src/Novell.Directory.Ldap.NETStandard/Connection.cs#L542

**Comment by linuxchata** [comment]
Any updates on this issue? We also have similar problem

**Comment by linuxchata** [comment]
When can we expect fix with PR https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/pull/120 being released?

**Comment by konrad-kruczynski** [comment]
@dsbenghe just a small follow-up: do you plan to release new version of the nuget package, containing this fix, soon?

**Comment by stevegreatrex** [comment]
I believe this change (i.e. replacing `_sock.Connect(ipEndPoint)` with `_sock.ConnectAsync(ipEndPoint).WaitAndUnwrap(ConnectionTimeout)`) may be causing some performance issues when running under docker.

Before I submit a PR, is there a reason that the following wouldn't achieve the desired result?
```csharp
_sock.ReceiveTimeout = _sock.SendTimeout = ConnectionTimeout;
_sock.Connect(ipEndPoint);
```
