### ISSUE TITLE
Recursively get group members is slow

### ISSUE THREAD

**Issue by NanFengCheong** [dsbenghe/Novell.Directory.Ldap.NETStandard#112]
Hi,

Below filter take more than 3 minutes to get the 13 records.
Is it possible to optimize this?
(&(objectCategory=person)(objectClass=user)(memberOf:1.2.840.113556.1.4.1941:=CN=GroupName))

**Comment by dsbenghe** [comment]
This doesn't seem to be related to this library.

Please check the same query using some of the open-source ldap tools.
