### ISSUE TITLE
Connecting over ssl: The remote certificate is invalid according to the validation procedure.

### ISSUE THREAD

**Issue by kaiiorg** [dsbenghe/Novell.Directory.Ldap.NETStandard#113]
My application is built on dotnet core 2.2 and I'm trying to trying to use the secure bind method as shown in the `SecureBind` example, but I get `The remote certificate is invalid according to the validation procedure.`, which I assume means the system doesn't trust the certificate.

I tried to use the method used in the `InteractiveSSL` example to validate the ssl cert, but I can't figure out how to install and use the `Mono.Security.X509` and `Mono.Security.Cryptography` assemblies required to event attempt it. My googlefu leads me to nothing. Maybe they don't support dotnet core?

**Comment by dsbenghe** [comment]
Don't use the samples as gospel. Are there for historical reasons and as a hint, but some of the things are outdated.

Check the tests for samples how to connect via SSL.
