### ISSUE TITLE
LDAPS docker, linux container

### ISSUE THREAD

**Issue by Henkolicious** [dsbenghe/Novell.Directory.Ldap.NETStandard#116]
Hi,

I'm trying to upgrade ldap to ldap(s) in an .NET Core application running in a linux docker container.
Currently using the latest Novell NuGet release (3.0.1)

Build step
<pre>
ADD xxx_AB_Root_CA.crt /usr/local/share/ca-certificates/xxx_AB_Root_CA.crt
RUN chmod 644 /usr/local/share/ca-certificates/xxx_AB_Root_CA.crt 
RUN update-ca-certificates
</pre>
Warning:
<pre>Updating certificates in /etc/ssl/certs...
<span style="color: red;">WARNING: xxx_AB_Root_CA.pem does not contain a certificate or CRL: skipping</span>
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.</pre>
Adding mono path variable: 
(1.4) https://www.microfocus.com/documentation/edirectory-developer-documentation/ldap-libraries-for-c-sharp/cnet.pdf
<pre>
ENV MONO_PATH=/app
</pre>

But the .dll is called a bit different from the .pdf file `Novell.Directory.Ldap.NETStandard.dll
`

From the .NET Core code I now try to connect to the AD like so:

<pre>
var userNameAndDomainName = $"{userRequest.UserName}@{_domainName}";

using (var connection = new LdapConnection { SecureSocketLayer = true })
{               
    connection.Connect(_domainName, LdapConnection.DefaultSslPort);
    connection.Bind(userNameAndDomainName, userRequest.Password);

    if (!connection.Bound)
        throw new UnauthorizedAccessException($"User {userRequest.UserName} not found in Aactive Directory.");

 // ...
</pre>

Which results in the following error:
`The remote certificate is invalid according to the validation procedure.`

It works just fine in my local windows 10 environment **_or_** if I ignore the certificate validation in docker linux container like: `                connection.UserDefinedServerCertValidationDelegate += delegate { return true; };`. 

Any idea where I'm going wrong?

**Comment by dsbenghe** [comment]
1. This library doesn't have anything to do with Mono. That was the original Novell version of the library.
2. This library doesn't do anything special in order to be able to connect via ssl. If you use pure .net core Socket/SslStream or an https client you will have the same problem to solve.

**Comment by Henkolicious** [comment]
Alright, thanks for the response.
