### ISSUE TITLE
Support for TLS. Different verisons.

### ISSUE THREAD

**Issue by Heber94** [dsbenghe/Novell.Directory.Ldap.NETStandard#117]
As a newbie, I have seen that STARTTLS is supported, but I'm not sure if that means that standard TLS is too. I guess it is, as SSL is also supported, but would like to have confirmation.

Sorry to bother with this, as it is probably easy to find, but I can't confirm it.
Best regards.

**Comment by Heber94** [comment]
Hi,
Can anyone confirm it?
Best regards.

**Comment by dsbenghe** [comment]
yes, it is supporting TLS. Internally the library uses authenticateasclientasync - https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.authenticateasclientasync?view=netcore-2.1
