### ISSUE TITLE
FetchSchema gets IndexOutofRange Exception

### ISSUE THREAD

**Issue by MornaK** [dsbenghe/Novell.Directory.Ldap.NETStandard#118]
After updating to the new 3.0.x from 2.3.8 (and adapt for the new constant & syntax), the FetchSchema() method throws an exception, some index gone rogue

**Comment by MornaK** [comment]
It seems that in the class LdapSchema, the change of type definition of _idTable & _nameTable implies a change in the way to initialize it...

So in `src/LdapSchema.cs` lines 162-163:
` _idTable[i] = new Dictionary<string, LdapSchemaElement>();`
`_nameTable[i] = new Dictionary<string, LdapSchemaElement>();`

should be replaced by:
`_idTable.Add(new Dictionary<string, LdapSchemaElement>());`
`_nameTable.Add(new Dictionary<string, LdapSchemaElement>());`

![image](https://user-images.githubusercontent.com/7156422/74328366-03a41080-4d8e-11ea-8d06-a84a258ce64b.png)


Or something similar...

Anyhow,  thanks for the project. You're doing a very fine job, keep going!

**Comment by dsbenghe** [comment]
fixed in 3.0.3
