### ISSUE TITLE
Novell.Directory.Ldap.NETStandard never authenticate with created user

### ISSUE THREAD

**Issue by DAREAS** [dsbenghe/Novell.Directory.Ldap.NETStandard#119]
Dear ones.

I developed an authentication system with the communication announcement.
The system creates a user with the following code:
` var normalizeFirstName = user.FirstName.RemoveAccents().ToLower();
            var normalizeLastname = user.LastName.RemoveAccents().ToLower();
            var dn = $"cn={normalizeFirstName}.{normalizeLastname},{_settings.ContainerName}";
           

 user.Cn = $"{normalizeFirstName}.{normalizeLastname}";

            var attributeSet = new LdapAttributeSet
            {
                new LdapAttribute("instancetype", "4"),
                new LdapAttribute("objectcategory", $"cn=Person,cn=Schema,cn=Configuration,{this._settings.DomainDistinguishedName}"),
                new LdapAttribute("objectclass", new[] {"top", "person", "organizationalPerson", "user", "inetOrgPerson"}),
                new LdapAttribute("memberof", new[] {"CN=Administrators", "CN=Users", "DC=company", "DC=local"}),
                new LdapAttribute("cn", user.Cn),
                new LdapAttribute("samaccountname", $"{normalizeFirstName}.{normalizeLastname}"),
                new LdapAttribute("userprincipalname", user.UserName),
                new LdapAttribute("userpassword", user.Password),
                new LdapAttribute("useraccountcontrol", user.MustChangePasswordOnNextLogon ? "544" : "512"),
                new LdapAttribute("givenname", user.FirstName),
                new LdapAttribute("sn", user.LastName),
                new LdapAttribute("mail", user.EmailAddress)
            };
            
            if(!string.IsNullOrWhiteSpace(user.EmployeeID))
            {
                attributeSet.Add(new LdapAttribute("employeeId", user.EmployeeID));
            }

            if (user.DisplayName != null)
            {
                attributeSet.Add(new LdapAttribute("displayName", user.DisplayName));
            }

            if (user.Description != null)
            {
                attributeSet.Add(new LdapAttribute("description", user.Description));
            }
            if (user.Phone != null)
            {
                attributeSet.Add(new LdapAttribute("telephoneNumber", user.Phone));
            }
            if (user.Address?.Street != null)
            {
                attributeSet.Add(new LdapAttribute("streetAddress", user.Address.Street));
            }
            if (user.Address?.City != null)
            {
                attributeSet.Add(new LdapAttribute("l", user.Address.City));
            }
            if (user.Address?.PostalCode != null)
            {
                attributeSet.Add(new LdapAttribute("postalCode", user.Address.PostalCode));
            }
            if (user.Address?.StateName != null)
            {
                attributeSet.Add(new LdapAttribute("st", user.Address.StateName));
            }
            if (user.Address?.CountryName != null)
            {
                attributeSet.Add(new LdapAttribute("co", user.Address.CountryName));
            }
            if (user.Address?.CountryCode != null)
            {
                attributeSet.Add(new LdapAttribute("c", user.Address.CountryCode));
            }
            
            var newEntry = new Novell.Directory.Ldap.LdapEntry(dn, attributeSet);

            using (var ldapConnection = this.GetConnection())
            {
                ldapConnection.Add(newEntry);
            }`

And authenticate with follow code:

`public bool Authenticate(string distinguishedName, string password)
        {
            var domainUser = string.IsNullOrWhiteSpace(distinguishedName) ? 
                _settings.Credentials.DomainUserName : distinguishedName;
            var userPassword = string.IsNullOrWhiteSpace(password) ?
                _settings.Credentials.Password : password;

            using (var ldapConnection = this.GetConnection())
            {
                try
                {
                    //ldapConnection.Connect(_settings.ServerName, _settings.ServerPort);

                    ldapConnection.Bind(LdapConnection.Ldap_V3, domainUser, userPassword);

                    return true;
                }
                catch (Exception ex)
                {
                    _logger.LogCritical($"Error ao autenticar no AD! > Message: {ex.Message}");
                    return false;
                }
            }
        }`

But never can't authenticate, because ldap returns Invalid Credentials.

Please, help me.

**Comment by dsbenghe** [comment]
My guess - you don't set correctly the password - probably you are using Active Directory. Please search the old issues where this issue was discussed multiple times.
