### ISSUE TITLE
LdapAttributeSet.GetAttribute throws exception instead of returning null when the attribute does not exist

### ISSUE THREAD

**Issue by kpwbo** [dsbenghe/Novell.Directory.Ldap.NETStandard#121]
https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/ef06c2f359e75be59f3963f59598a0ba3c7c5383/src/Novell.Directory.Ldap.NETStandard/LdapAttributeSet.cs#L84

A KeyNotFoundException is thrown when attrName does not match any attribute in the attribute set. The documentation above the function says that the function returns null in that case. Either the function should be changed to return null when there is no matching attribute or the documentation should be fixed to correctly describe the behavior of the function.

**Comment by igor-moskvitin** [comment]
As temporary fix:
```
public static LdapAttribute MaybeAttribute(this LdapAttributeSet set, string key) =>
            set.ContainsKey(key) ? set.GetAttribute(key) : null;
```

**Comment by dsbenghe** [comment]
Fixed the documentation
