### ISSUE TITLE
 attribute scoped query

### ISSUE THREAD

**Issue by mikeTWC1984** [dsbenghe/Novell.Directory.Ldap.NETStandard#123]
Is there a way to perform  attribute scoped query? For example if I need to get members of AD group (as a list of entries). In .net this can be achieved by specifying DirectorySearcher.AttributeScopeQuery property   (see powershell snippet below) 

```powershell
    $searcher = [adsisearcher]$domainLDAP
    $searcher.Filter ="(&(objectClass=group)(cn=SOME-ADGROUP))"
    $GroupResult = $searcher.findone()
    $GroupEntry = $GroupResult.GetDirectoryEntry()
    $searcher.DirectorySearcher.AttributeScopeQuery = "member"
    $searcher.SearchRoot = $GroupResult.Path
    $searcher.Filter = '(objectclass=Person)'
    $members = $searcher.FindAll()
```

**Comment by dsbenghe** [comment]
This seems to be an AD only feature. This library doesn't support any AD only feature.
