### ISSUE TITLE
If the LDAP-USER does not exist, no exception is thrown

### ISSUE THREAD

**Issue by FlorianJS** [dsbenghe/Novell.Directory.Ldap.NETStandard#125]
If the LDAP-USER does not exist, no exception is thrown

**Comment by dsbenghe** [comment]
more details needed.

**Comment by FlorianJS** [comment]
Hello, sorry, I'm creating a LdapConnection and call the Bind function when I pass to the Bind function String.Empty no LDAP error is thrown 

Here is a short example:

```
using (var LDAP = new LdapConnection())
{
   try
  {
      LDAP.Bind(String.Empty, password);
      isVerified = true;
                       
  }
  catch (LdapException)
  {
                       
  }
}
          
```

**Comment by dsbenghe** [comment]
you must have something wrong in your code as it throws an exception with invalid credentials. 

If you still think so please create a PR with a test which fails (see the run-opendj.bat for running a ldap server in a docker container)
