### ISSUE TITLE
LdapSearchConstraints.TimeLimit is effectively ticks

### ISSUE THREAD

**Issue by jcracknell** [dsbenghe/Novell.Directory.Ldap.NETStandard#126]
LdapSearchConstraints.TimeLimit appears to effectively be in ticks rather than milliseconds.

As best I can tell this gets passed to Message and is used to create a timeout here:
https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/5aec5ad61ba7bde5f2e99ab9718f1fbca35af5d4/src/Novell.Directory.Ldap.NETStandard/Message.cs#L258

Which then uses it as ticks here:
https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/5aec5ad61ba7bde5f2e99ab9718f1fbca35af5d4/src/Novell.Directory.Ldap.NETStandard/Message.cs#L500

**Comment by dsbenghe** [comment]
Current code seems to be correct to me. I improved the code to be more explicit. If you still think is incorrect let me know.
