### ISSUE TITLE
The remote certificate is invalid according to the validation procedure

### ISSUE THREAD

**Issue by aleksvujic** [dsbenghe/Novell.Directory.Ldap.NETStandard#129]
We are developing a **.NET Core 3.1** web application. We were using version **2.3.8** and everything worked fine. After upgrading to version **3.2.0** we encountered the following exception when executing `connection.Connect(url, port)`.

```
System.Security.Authentication.AuthenticationException: 'The remote certificate is invalid according to the validation procedure.'
```

Here is the code that we are using for both 2.3.8 and 3.2.0. It worked for 2.3.8 but fails for 3.2.0.

```
try
{
	using (var connection = new LdapConnection { SecureSocketLayer = true, ConnectionTimeout = 2000 })
	{
		connection.Connect("1.2.3.4", 123);
		connection.Bind("domain\\username", "password");
		if (connection.Bound)
		{
			Console.WriteLine("OK");
		}
	}
}
catch (LdapException ex)
{
	Console.WriteLine(ex.Message);
}
```

What has changed between 2.3.8 and 3.2.0?

**Comment by dsbenghe** [comment]
It could be because of this fix - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/105

Register a delegate for RemoteCertificateValidationCallback and you can see if this is the case.

**Comment by aleksvujic** [comment]
If I understand correctly, it shouldn’t have worked in 2.3.8 either but it did because there was a bug?

**Comment by dsbenghe** [comment]
Yes. It was the wrong default. You should be able to see if this is the case if you register the delegate and see why it fails to validate the certificate.

**Comment by aleksvujic** [comment]
Yes, it works with `ldapConnection.UserDefinedServerCertValidationDelegate += (sender, certificate, chain, errors) => true;`. Thank you.

**Comment by dsbenghe** [comment]
Not a good idea to by-pass the certificate validation via the callback. Better find what is wrong with the certificate validation and fix it.
