### ISSUE TITLE
Vs 2017 netcore 1.1 Doesnt Compile

### ISSUE THREAD

**Issue by Diaskhan** [dsbenghe/Novell.Directory.Ldap.NETStandard#13]
Error	MSB6006	"csc.exe" return with code -532462766.	AD_CHECK_NC10	
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets	71	

Using VS 2017, Have added nuget package. It doesnt compiles.
[AD_CHECK_NC10.zip](https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/files/946134/AD_CHECK_NC10.zip)

**Comment by dsbenghe** [comment]
We are using the library with no problems on linux and windows on net core 1.1. And your solution compiles and run fine for me.

Being .net standard 1.3 built library there isn't any reason why wouldn't run on any .net standard 1.3 compatible runtime.

**Comment by Diaskhan** [comment]
Can U provide Demo Project for VS 2017 net core 1.1  
csproj type project ??

**Comment by Diaskhan** [comment]
When I installed  VS 2017, I have checkhed optinos only cross-platform net core.
Maybe I need Install other components ???

**Comment by dsbenghe** [comment]
Sorry, but this is not related with this library but with your environment; probably will fail with any other nuget package.
