### ISSUE TITLE
Race condition in MessageVector

### ISSUE THREAD

**Issue by ericbriere-git** [dsbenghe/Novell.Directory.Ldap.NETStandard#130]
I found a problem with MessageVector class where the Add method does not lock the collection, which results to an error (collection updated while iterating). The end result of the bug is that LDAP connection drops during large iterations (Connect error). I do have a fix locally. What is the good process to submit the pull request?

**Comment by dsbenghe** [comment]
No specific process to submit a PR - just the usual github process.

**Comment by dsbenghe** [comment]
The fix for this will be in the next of 3.x.
