### ISSUE TITLE
Adding user to groups

### ISSUE THREAD

**Issue by ashtek19** [dsbenghe/Novell.Directory.Ldap.NETStandard#136]
I'm trying to add a user to a group, I followed this link - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/master/original_samples/Samples/AddUserToGroup.cs

However I see error - "**Error in attribute conversion operation, data 0, v3839**"

Does the above sample have any pre-requisites to be setup in active directory? Creating the user works fine, but adding to group fails. Are there other ways of adding user to group, for ex. find a group by name and add the user. 
Above sample has multiple steps - adding Group's DN to User's attributes _groupMemberShip_  and _securityEquals_ and then adding User's DN to Group's attributes _uniqueMember_ and _equivalentToMe_

**Comment by dsbenghe** [comment]
This was discussed before - see here - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/21
