### ISSUE TITLE
How to create SASL connection

### ISSUE THREAD

**Issue by CerealG** [dsbenghe/Novell.Directory.Ldap.NETStandard#137]
Hello,

I want to create a SASL connection with the following settings.
I searched but I can't find a doc that clearly explains how to create this type of connection.
Could you help me?

Thank you :)
![image](https://user-images.githubusercontent.com/69843185/95552995-fd922c80-0a0d-11eb-9a9c-fc466a7167a0.png)

**Comment by dsbenghe** [comment]
Not supported. There is already an issue open about this - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/28
