### ISSUE TITLE
LdapAttributeSet GetAttribute documentation has conflicting information

### ISSUE THREAD

**Issue by mattj23** [dsbenghe/Novell.Directory.Ldap.NETStandard#139]
The `LdapAttributeSet`'s `GetAttribute` method states that if an attribute is not found a `null` will be returned

[LdapAttributeSet.cs](https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/master/src/Novell.Directory.Ldap.NETStandard/LdapAttributeSet.cs), see line 70 and106

However, the actual implementation (line 86 and 154) simply uses the `[...]` operator on the dictionary base class, which instead throws a `KeyNotFoundException` when the key is missing (as is also specified in the documentation in lines 83 and 150).

It seems that older versions of this library did return a `null` value if the key wasn't found, as I discovered this issue through broken code in another project.  It would be helpful to clarify in the documentation which the intended behavior is.

**Comment by dsbenghe** [comment]
The most recent version has the documentation corrected.
