### ISSUE TITLE
Validating user credentials.

### ISSUE THREAD

**Issue by codyskidmore** [dsbenghe/Novell.Directory.Ldap.NETStandard#14]
Please check the example for authenticating users. I believe cn.Bind() actually authenticates application credentials, not user credentials. 

cn.Bind("<<application dn>>", "<<application password>>");

The code for validating user credentials should be:

var passwordAttr = new LdapAttribute("userPassword", "user's secret password");
var passwordMatches = cn.Compare("User's DN", passwordAttr);

See the following link for reference.
ftp://sdk.provo.novell.com/ndk/ldapcsharp/Samples/Samples/VerifyPassword.cs

**Comment by dsbenghe** [comment]
Bind can authenticate any "user" defined in the directory. Sometimes this is an application user, sometimes a real user - we are using it with both (https://www.ldap.com/the-ldap-bind-operation)

About compare (which I'm not using it anyway) - I doubt that using compare is triggering all the security checks (e.g. account is locked if you did it x times with the wrong password ... ).

**Comment by codyskidmore** [comment]
Thanks for the head's up re: compare. Do you have any suggestions for authenticating users in a scenario where you musts first connect to eDirectory using application credentials. Then use the connection to validate an individual's credentials?

**Comment by dsbenghe** [comment]
You could bind again with the individual credentials after you did with application credentials.

**Comment by codyskidmore** [comment]
It turns out our client got it wrong. The correct way is to bind the connection directly to an individual's credentials.
