### ISSUE TITLE
Connection error (91) with SSL port 636 on docker .NET Core 3.1

### ISSUE THREAD

**Issue by mezhavecis** [dsbenghe/Novell.Directory.Ldap.NETStandard#141]
There is some problem with SSL connection on docker and linux machines with .NET Core 3.1.  I'm getting error 91 on connect.  On windows machines are no problems.

```
Authentication failed because the remote party has closed the transport stream.
   at Novell.Directory.Ldap.AsyncExtensions.WaitAndUnwrap(Task task, Int32 timeout)
   at Novell.Directory.Ldap.Connection.Connect(String host, Int32 port, Int32 semaphoreId)
```
    
```
using (var cn = new LdapConnection())
                    {                       
                        cn.SecureSocketLayer = true;
                        //cn.UserDefinedClientCertSelectionDelegate += Cn_UserDefinedClientCertSelectionDelegate;
                        cn.UserDefinedServerCertValidationDelegate += new Novell.Directory.Ldap.RemoteCertificateValidationCallback(Cn_UserDefinedServerCertValidationDelegate);
                        cn.ConnectionTimeout = 0;// 10000
                        cn.Connect(server, 636);
                    }
private static bool Cn_UserDefinedServerCertValidationDelegate(object sender, X509Certificate certificate, X509Chain chain, System.Net.Security.SslPolicyErrors sslPolicyErrors)
        {
            return true;
        }

```
I copied and checked function Connect and possible problem is in this row with sslstream.AuthenticateAsClientAsync
https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/master/src/Novell.Directory.Ldap.NETStandard/Connection.cs#L559

If I add additional parameters such enabledSslProtocols  as TLS, stream is not crashing.
  sslstream.AuthenticateAsClientAsync(host, null, System.Security.Authentication.SslProtocols.Tls, false ).WaitAndUnwrap(ConnectionTimeout);

I tried with StartTLS method, but this also didn't work. 
Maybe is other way to get work secure connection with LDAP server?

**Comment by se** [comment]
It could be a certificate issue. Did you try to add the root certificate into the container?

**Comment by dsbenghe** [comment]
My guess is that the following is happening: by default the SslProtocols.None will be used which allows the OS to select the best protocol but it will block some protocols which are considered un-secure (which likely on your os include tls1.0). Probably because your ldap server doesn't support TLS > 1.0 it fails to connect using OS default selection, but it works when you specify directly the version.

See here for details about SslProtocols: https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=netcore-3.1#System_Security_Authentication_SslProtocols_None

Maybe you can check this theory?

**Comment by dsbenghe** [comment]
Since 3.6.x new feature was introduced so the SslProtocols which can be configured e.g.

```          
var options = new LdapConnectionOptions()
    .UseSsl()
    .ConfigureSslProtocols(SslProtocols.Ssl2);
using var ldapConnection = new LdapConnection(options);
ldapConnection.Connect(...)
```

This will allow tweaking the SSL protocols choice - even using the ones considered obsoleteS.

**Comment by mezhavecis** [comment]
Hello!

I'm sorry for delayed answer. There was problems to check existing LDAP settings. After investigation I found that current LDAP server supporting only TLS 1.0 and TLS 1.1.  SslProtocols.None  is not working on Docker. Certificate revocation procedure is starting only after secure channel is established. 

I verified library code 3.6.x with latest features using LdapConnectionOptions options class and authentication working fine with TLS on Docker. Please, can you release a nuget package ?

**Comment by dsbenghe** [comment]
3.6.0 is published.
