### ISSUE TITLE
How to handle the flow that user must change the password in first login

### ISSUE THREAD

**Issue by xrkolovos** [dsbenghe/Novell.Directory.Ldap.NETStandard#150]
How to handle the flow that user must change the password in first login?
Any sample code? Thank you

**Comment by se** [comment]
What do you mean handle? What do you want to do? Can you be a more specific?

If you want to know that user must change his/her password at first login, you need to check pwdLastSet attribute.

**Comment by xrkolovos** [comment]
The senario is the following. The user has checked the "User must change password at next log on". The attribute pwdLastSet has the value (never).

I am trying to run connection.Bind(userDn, password) and I get the error "Invalid Credentials" -> "80090308: LdapErr: DSID-0C090446, comment: AcceptSecurityContext error, data 773, v4563\0"

So, I was asking if there is a sample code for this senario. I searched that this code is [773 - user must reset password ](https://dotcms.com/docs/latest/active-directory-error-codes#773)

If, the i can't make the connection with this user, propably i would need an Admin User to connect and change the password. Is this the right way?

**Comment by se** [comment]
Nope. You change that user's password with same username and password. You don't need anything else. But I really don't know the process with the Novell.Directory.Ldap.NETStandard. 

For your case (if you are using this lib) Admin User/Password could be needed.
