### ISSUE TITLE
Stability Status of 4.0.0 beta-1?

### ISSUE THREAD

**Issue by RacerDelux** [dsbenghe/Novell.Directory.Ldap.NETStandard#153]
What is the status of 4.0.0 beta-1? Are there any known active issues?

I am implementing this and I really need access to the async functionality, but the release needs to be stable first.

Thanks!

(I suppose I can do the while loop workaround if needed...)

**Comment by dsbenghe** [comment]
There are no known active issues.
Stability: the stress tests never failed.

**Comment by RacerDelux** [comment]
Got it thanks! (Late reply courtesy of Texas ice storms)
I will give it a whirl and report back if any issues arise. I appreciate the library thus far!
