### ISSUE TITLE
Change LdapSearchResults to IAsyncEnumerable

### ISSUE THREAD

**Issue by nesc58** [dsbenghe/Novell.Directory.Ldap.NETStandard#155]
Can we drop support for `.netstandard 1.3` in favor to use [IAsyncEnumerable](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.iasyncenumerable-1?view=dotnet-plat-ext-5.0)?

`LdapSearchResults` should inherit `IAsyncEnumerable ` to use be full async.  We can use `await` instead of `.GetAwait().GetResult()` in methods like `GetEnumerator` (--> `GetEnumeratorAsync`) or  the inner `Next`  (--> `NextAsync`) 

[IAsyncEnumerable](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.iasyncenumerable-1?view=dotnet-plat-ext-5.0) will be supported in .netstandard >= 2.1 . So this will lead into another breaking change.
For compatibility reasons we can install [Microsoft.Bcl.AsyncInterfaces](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/ ) for .netstandard 2.0

**Comment by dsbenghe** [comment]
This was exactly the plan to get rid of the last *.GetAwaiter().GetResult() (in fact there is another one but for a very likely mostly unused feature).
- drop support for 1.3 in 4.0 version
- move to IAsyncEnumerable.

**Comment by nesc58** [comment]
I found `StartSearchAndPolling` in `PSearchEventSource` (`LdapEventSource`) where GetAwaiter is still used. 

I cannot solve it for now, because I don't know how to change e.g. `public event SearchResultEventHandler SearchResultEvent` to use async/await.

I am sure we find a proper solution for this

**Comment by dsbenghe** [comment]
that usage is the one I mentioned in my previous reply as "in fact there is another one but for a very likely mostly unused feature".

**Comment by nesc58** [comment]
Is there an advantage to use `event` for them? We are changing the API, so we can change this part too e.g. to regular methods like
`AddSearchResultEvent` and `RemoveSearchResultEvent`

The signature can look like the following:
```
public async Task AddSearchResultEventAsync(SearchResultEventHandler handler)
{
    _searchResultEvent += handler;
    await ListenerAddedAsync().ConfigureAwait(false);
}

public void RemoveSearchResultEventAsync(SearchResultEventHandler handler)
{
    _searchResultEvent -= handler;
    ListenerRemoved();
}
```

For sure it is a breaking change and a completely different call but for me this seems to be valid for me.
What do you think?

**Comment by dsbenghe** [comment]
That functionality is like the original from 20 years ago and I just converted it to .net standard. I doubt that too many people will implement it like this these days. And I don't think too many people are in fact using that functionality.

My thinking about this was to just remove that functionality in 4.0 and eventually offer something more raw and simple i.e. don't assume how this is used by users. There is also an issue open about this - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/152 - so a functional test needs to be added for this.

**Comment by dsbenghe** [comment]
Everything is async now in 4.0.0. Closing this.
