### ISSUE TITLE
TlsException: Failed to create UnityTls context - error code: UNITYTLS_INVALID_ARGUMENT

### ISSUE THREAD

**Issue by viniciusbenite** [dsbenghe/Novell.Directory.Ldap.NETStandard#156]
Hi, hoping everything is well with you.

I am trying to stablish a ldap connection in a Unity application, but I got the error described in the title. There isn't much information around it. Here is the code:

```
Novell.Directory.Ldap.LdapConnection connection = new Novell.Directory.Ldap.LdapConnection { SecureSocketLayer = true };

Debug.Log("Validating certs");

connection.UserDefinedServerCertValidationDelegate += new

Novell.Directory.Ldap.RemoteCertificateValidationCallback(MyRemoteCertificateValidationCallback);

Debug.Log("connecting user: " + username);
connection.Connect(domain, port);

try
{
    connection.Bind(username, password);

    if (connection.Bound)
    {
        Debug.Log("bound to LDAP");
    }
}
catch (Exception e)
{
    Debug.Log("user auth failed: " + e.Message);

    throw new Exception("bind failed");
}

connection.Disconnect();
```

The error is throw in LdapConnection.Connect method.

I appreciate any help.

Kind regards.

**Comment by dsbenghe** [comment]
You need to take a more detail look at the exception.

But assuming that you have a server that is really running the most likely cause is un-matching ssl/tls protocol version negotiation. You can read more here - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/141. Basically, you will likely need to down-grade your ssl/tls version as probably the client wants to use a more secure version than your server is configured with.

**Comment by viniciusbenite** [comment]
Thank you for the swift response.

Indeed, I was missing the ss/tls protocol version. This answer solved: 

https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/141#issuecomment-752967168

Thanks!
