### ISSUE TITLE
Does this library currently not support UWP?

### ISSUE THREAD

**Issue by djkaosun** [dsbenghe/Novell.Directory.Ldap.NETStandard#157]
Exception is thrown and Connect is not possible. System.Net.Internals.SocketExceptionFactory+ExtendedSocketException is thrown when LdapConnection.Connect() is executed.

I'm developing a UWP app and have enabled all the Capabilitys in Package.appxmanifest. Does this library currently not support UWP? The library currently in use is version 3.6.0.

**Comment by dsbenghe** [comment]
Yes, it does according to MS documentation - https://docs.microsoft.com/en-us/dotnet/articles/standard/library.

I, personally, haven't used it so I can comment on it. Maybe others can comment.

Look more at the exception details - for sure there is more than just the exception type.

**Comment by djkaosun** [comment]
Thank you for your answer.

The message of the thrown Exception was:
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.

Maybe there is a special limitation in using sockets directly in UWP apps.

I will try to isolate in more detail what is happening.

**Comment by dsbenghe** [comment]
That looks like a generic error with UWP and socket permissions: so probably nothing socket related works for you. I will close this issue and please feel free to re-open it if you go over the socket problem and get an error related specifically to this library.
