### ISSUE TITLE
LdapEntry Handle Missing Keys

### ISSUE THREAD

**Issue by RacerDelux** [dsbenghe/Novell.Directory.Ldap.NETStandard#159]
If you are fetching values from an `LdapEntry`, and want to make sure they key exists (if the key does not exist, you get an exception), you have to do the following:
```cs
entry.GetAttributeSet().ContainsKey('TelephoneNumber') ? entry.GetAttribute('TelephoneNumber').StringValue : "111-222-3333"
```
While this is not terrible, it seems a little odd that `LdapEntry` does not either:

a) Properly return null if the key does not exist without throwing an error
b) Implement its own `ContainsKey` method that simply calls `ContainsKey` on the `LdapAttributeSet`

Personally I would prefer option a, as you could rewrite the above code as:
```cs
entry.GetAttribute('TelephoneNumber')?.StringValue ?? "111-222-3333"
```
Just much cleaner and has a more expected outcome.

**Comment by dsbenghe** [comment]
I'm not a big fan of returning null - of course, this is subjective. So I would not be for returning null. Of course, if someone prefers returning null, it can always be implemented as an extension method on top.

But for the second point, yes, the LdapEntry should be nicer to use i.e. not needing to go through  GetAttributeSet.

**Comment by nesc58** [comment]
What is about a well known TryGet pattern: `bool TryGet (string attributeName, out LdapAttribute foundAttribute)`?

**Comment by RacerDelux** [comment]
@nesc58 
+1 to `FindOrDefault`. This would be a very good solution.
I have a love hate with Null returns... They can be useful, but can also be pretty annoying.
The default return value if not set could be null also. So calling `FindOrDefault('AttributeName')` would return null if not found since the 2nd argument was not given.

**Comment by photoacross** [comment]
Many thanks this saved me a bit of a headache - had to modify some VB code which was throwing up an error 'The given key was not present in the dictionary' for certain usernames.  When comparing LDAP entries, some of these users did not have a particular attribute, hence the above error.

VB code below if anyone finds that useful. 

`If _ldapUser.GetAttributeSet().ContainsKey("sn") Then
            sname = _ldapUser.GetAttribute("sn").StringValue
        Else
            sname = "Unknown"
        End If`

**Comment by rilehudd** [comment]
@nesc58 
`ldapEntry.TryGetAttribute(TestAttributeName, out var r) ? r.StringValue ?? "111-222-3333" : "111-222-3333"`

Why allow the attribute to return null in this case? It seems unneeded if you are already building the Try* pattern. 
Why not return false if the attribute value type is null? Then you would simply have: 
`ldapEntry.TryGetAttribute(TestAttributeName, out var r) ? r.StringValue  : "111-222-3333"`

But, maybe there is a reason you would want to get an attribute that has no value? (not even sure that is possible).

**Comment by nesc58** [comment]
In some cases I don't care if the key exists or not I just want to have a value without typing a lot of if cases e.g. if the attribute not exists, if the found attribute is null, if the found attribute not contains any values and so on. 

`StringValue` can return null when the attribute exists without any values. Maybe this is really uncommon but should be handled correctly.
So in this case the `r.StringValue` can be null. In a project where no nulls are allowed the fallback have to been used.

In other projects I have solved this problem using the following pattern:
```
public string? GetNullableStringAttributeOrDefault([NotNull] string attributeName, string? fallback)
=> Attrs.TryGetValue(attributeName, out var attribute) ? attribute.StringValue : fallback;

public string GetStringAttributeOrDefault([NotNull] string attributeName, string fallback)
=> GetNullableStringAttributeOrDefault(attributeName, fallback) ?? fallback;

```

This allows the caller to decide if a nullable string is allowed or not. To handle nulls or not really depeneds on the project.
When the project allows nulls and don't want to use a default value the GetNullableStringAttributeOrDefault can be used. When nulls are permitted the GetStringAttributeOrDefault can be used.
The naming is not quite accurate yet, but I think the idea becomes more clear

**Comment by dsbenghe** [comment]
Some of the suggestions in this issue were implemented in latest.

**Comment by nesc58** [comment]
@dsbenghe is there a roadmap or plan for releasing the version 4.0.0?
