### ISSUE TITLE
Connecting to port 639

### ISSUE THREAD

**Issue by codyskidmore** [dsbenghe/Novell.Directory.Ldap.NETStandard#16]
Where can I find an example for connecting to eDirectory over SSL? I switched ports and set SecureSocketLayer to true. When I open the connection an exception occurs.

**Comment by dsbenghe** [comment]
Maybe this will help - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/6
Also the tests are running using ssl and tls

**Comment by codyskidmore** [comment]
This probably means I actually have a certificate issue, not an SSL issue.
