### ISSUE TITLE
Getting Unavailable Critical Extension ERROR

### ISSUE THREAD

**Issue by Vaseem88** [dsbenghe/Novell.Directory.Ldap.NETStandard#160]
@dsbenghe While trying to search the LDAP data using **LdapVirtualListControl**, I am getting error as this 

**The search request cannot be processed because it contains a critical control with OID 2.16.840.1.113730.3.4.9 that is not supported by the Directory Server for this type of operation**

However it works fine with using **LdapVirtualListControl** but only gets 100000 records and returns a error for search limit. So I tried to use the **LdapVirtualListControl** to get the data by batches and landed up with this error **Unavailable Critical Extension**

I have tested this in a OpenDJ LDAP server.
Please refer the screenshot for the error
![error](https://user-images.githubusercontent.com/23305215/110621923-d1e3c000-81c0-11eb-9435-0ed64c139b8f.png)

 

@mstum @tibel @marcin-krystianc @ubik @metacube @jfharvie @martindrlik @Kim-SSi @konrad-kruczynski 
@dsbenghe Could you please help me resolve this issue with this error

**Comment by marcin-krystianc** [comment]
I think this is a problem on the `OpenDJ LDAP` server side. To my understanding it doesn't support the `2.16.840.1.113730.3.4.9` extension or the support for is not enabled.

**Comment by Vaseem88** [comment]
@marcin-krystianc I verified in the OpenDJ LDAP server that the control `2.16.840.1.113730.3.4.9` is supported but I am not sure whether it is actually enabled. Do you have any idea on how I can check that ?

**Comment by dsbenghe** [comment]
Not clear from your description what works and what doesn't? 
ldapsearch --simplePageSize is using Simple Paged Results Control, not VLV. So, using Simple Paged Results Control with this library should work too. 
The error suggests that the VLV control is not enabled in OpenDJ.

**Comment by Vaseem88** [comment]
@dsbenghe  I checked with the both the implementation of the paged search (Simple Paged search and Virtual List View) but none of them worked, I am keep getting the same error (`Unavailable Critical Extension`). However when I verified whether the controls are supported I could see the both the paged search controls are listed under supported controls but I am not sure why It is not working with the code.
![image](https://user-images.githubusercontent.com/23305215/111640338-1c4ce880-8822-11eb-8868-3c7c1e9c50b8.png)
![image](https://user-images.githubusercontent.com/23305215/111640433-32f33f80-8822-11eb-8683-99d0c21210e9.png)


I also checked the Simple Paged search using the command line with the ldapSearch tool and found that to be working fine with the below code 
`ldapsearch --hostname opendj.com --port 389 --bindDN ""  --searchScope sub --baseDN dc=example,dc=com --simplePageSize 2 --countEntries "(objectclass=*)"
`
I also checked with some Microsoft documentation on how to use paged search from the below link but it is also not working, could you please help me with this on what am I missing here 
https://docs.microsoft.com/en-us/previous-versions/dotnet/articles/bb332056(v=msdn.10)?redirectedfrom=MSDN#running-a-paged-search

**Comment by dsbenghe** [comment]
It looks that you are having your own code to use the search controls.

Try to use the built-in methods of the library (since 3.5.x): ldapConnection.SearchUsingSimplePaging and ldapConnection.SearchUsingVlv. The implementation was tested using OpenDJ also.

**Comment by Vaseem88** [comment]
@dsbenghe as you suggested, I checked with both the built in methods of the library but still could not make the paged search working, Please refer the below screenshots for the same.
1. LDAP search without paging
![LDAP novel serach](https://user-images.githubusercontent.com/23305215/111777292-1fef7680-88d9-11eb-8f3d-69b229163468.png)
2. LDAP search with Simple paging
![novel paged search](https://user-images.githubusercontent.com/23305215/111777371-3695cd80-88d9-11eb-9e5c-c2038233e77a.png)
3. LDAP search using VLV
![image](https://user-images.githubusercontent.com/23305215/111777402-431a2600-88d9-11eb-9a2e-b1bcd830e5d6.png)


After adding the Novell library , Below is the code I have used to make the LDAP search requests
``
class Program
    {
        static void Main(string[] args)
        {
            var ldapHost = "opendj.com";
            var ldapPort = 389;
            LdapConnection conn = new LdapConnection();
            Console.WriteLine("Connecting to:" + ldapHost);
            conn.Connect(ldapHost, ldapPort);
            conn.Bind("", "");
            var _searchOptions = new SearchOptions(
                "",
                LdapConnection.ScopeSub,
                "(objectclass=*)",
                null);
            var _ldapSortControl = new LdapSortControl(new LdapSortKey("cn"), true);
            var result = conn.SearchUsingVlv(_ldapSortControl, _searchOptions, 20);


            try
            {
                var reslut = conn.Search("", LdapConnection.ScopeSub, "(objectclass=*)", null,false);
                var lsc = reslut.ToList();

                
                Console.WriteLine("Below is simple paged search");
                var res = conn.SearchUsingSimplePaging(_searchOptions, 20);

            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.ToString());

            }
            Console.WriteLine("test");
        }
    }
``

**Comment by dsbenghe** [comment]
Don't know what is your issue. This kind of error is thrown if the control is really missing/not enabled - and the error is coming from the ldap server. Check your opendj logs - you may find something helpful there.

The code repository has in the root a batch file that runs opendj in a container that is used for testing - you can try that to verify the correctness of the code.

**Comment by dsbenghe** [comment]
Closed this - this looks as ldap server configuration issue. Please re-open if you have more information to suggest otherwise.

**Comment by MartinSoka** [comment]
maybe it helps someone, but we've solved this by using a search filter after discovering this error here [https://ldapwiki.com/wiki/MaxTempTableSize](url)
