### ISSUE TITLE
Search by objectGUID attribute

### ISSUE THREAD

**Issue by thanhhactld** [dsbenghe/Novell.Directory.Ldap.NETStandard#162]
Currently, I want to search by objectGuid , but i dont know where is right format filter, anyone can help me please ?
here is my filter: 
```
filter = (&(objectGUID=60\E5\07\55\65\13\71\46\AC\49\6B\D8\AF\4A\EA\5D))
```

**Comment by dsbenghe** [comment]
This should help - https://ldapwiki.com/wiki/ObjectGUID
