### ISSUE TITLE
Fix this damn library and make it usable

### ISSUE THREAD

**Issue by Porkechebure** [dsbenghe/Novell.Directory.Ldap.NETStandard#166]
Searching users it's a nightmare.
You can delete a user doing LdapConnection.DeleteAsync("user")
but finding an user it's like building a rocket for the moon.
Damn, make it usable.

I have a AD called DOMAINEXAMPLE.net, with group Users where I neet to find user "hellouser"
How?
var search = await _connection.SearchAsync("DC=DOMAINEXAMPLE.net,DC=Users", LdapConnection.ScopeSub, "(&(sAMAccountName=hellouser))", null, false);

goes without error then when using "search" it throws error "0000202B: RefErr: DSID-0310082F, data 0, 1 access points
	ref 1: 'domainexample.net.users'

How to do?

**Comment by dsbenghe** [comment]
Don't know why I kept this issue open for such a long time ...

**Comment by Porkechebure** [comment]
> Don't know why I kept this issue open for such a long time ...

Easy, because you can't do what it has to be asked and you can't fix my remark.
Basically library is a crooked ad implementation with lot of unintelligible code which requires lot of side documentation to make it work
