### ISSUE TITLE
how can i get the 'System.DirectoryServices.AccountManagement's Enabled Attr

### ISSUE THREAD

**Issue by DrZhong** [dsbenghe/Novell.Directory.Ldap.NETStandard#167]
at System.DirectoryServices.AccountManagement i can use  AuthenticablePrincipal's Enabled to get the user is or not ative.
how can i get this attribute in  'Novell.Directory.Ldap.NETStandard' code

![image](https://user-images.githubusercontent.com/8085571/115980974-31582c80-a5c3-11eb-8891-d63b945a3b3b.png)

**Comment by dsbenghe** [comment]
This should help: https://stackoverflow.com/questions/9509222/retrieving-only-enabled-accounts-on-active-directory
