### ISSUE TITLE
Bind Hangs on error

### ISSUE THREAD

**Issue by MarkoBL** [dsbenghe/Novell.Directory.Ldap.NETStandard#168]
Hi,

I just tried to use this library for user authentication, but for some reason, Bind(Async) hangs on an error (tested it with 3.6.0 and 4.0.0 beta). When the dn and password are correct, everything works as expected. But when I use a wrong dn or password, the library hangs, and I get the following line in the visual studio output: `Exception thrown: 'Novell.Directory.Ldap.LdapException' in System.Private.CoreLib.dll`  

Here's my code:

```
            try
            {
                var options = new Novell.Directory.Ldap.LdapConnectionOptions().ConfigureRemoteCertificateValidationCallback((sender, certificate, chain, errors) => true);
                using (var cn = new Novell.Directory.Ldap.LdapConnection(options))
                {
                    await cn.ConnectAsync("core1", 389);
                    await cn.StartTlsAsync();
                    await cn.BindAsync("CN=name,CN=Users,DC=exampe,DC=com", "test");
                }
            }
            catch (Exception ex)
            {

            }
```

**Comment by MarkoBL** [comment]
I downloaded the code and I get two exceptions. 

1st in `LdapResponse:ChkResultCode`
```
LdapException: Invalid Credentials (49) Invalid Credentials
LdapException: Server Message: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1
LdapException: Matched DN:
```

2nd in `Connection:DestroyClone`
```
LdapException: Connection closed by the application disconnecting (91) Connect Error
```

**Comment by MarkoBL** [comment]
Seems like I found the culprit. When the connection is being disposed, it hangs in
`Connection.Destroy` in `_readerThreadEnclosure.Stop();`, to be exact during `_enclosedThread.Join();`.

**Comment by dsbenghe** [comment]
What framework? I added a test with exactly this scenario and is passing on netcore3.1/net5 using openldap/opendj.

**Comment by MarkoBL** [comment]
I'm using netcore 3.1 and connect to a samba active diretory domain controller on debian 10 `Samba version 4.9.5-Debian`.

**Comment by dsbenghe** [comment]
likely same as #101
