### ISSUE TITLE
How to decode userParameters attribute?

### ISSUE THREAD

**Issue by michaelsync-mt** [dsbenghe/Novell.Directory.Ldap.NETStandard#170]
I think the Remote Service Profile (Terminal Service) is in userParameters attribute. I am looking for a way to decode the data. 

Or, Does this library support ADSI extension?

**Comment by dsbenghe** [comment]
This library is purely an LDAP client library. It doesn't have any specific Active Directory functionality. You can layer that yourself on top of the library i.e. read the attribute like any other attribute and decode it.

This https://stackoverflow.com/questions/47659621/how-can-i-read-the-content-of-the-user-parameters-attribute-of-an-active-directo/47659622 looks like a good start
