### ISSUE TITLE
Is account status implemented? If yes how? (account disabled, password expired etc)

### ISSUE THREAD

**Issue by Porkechebure** [dsbenghe/Novell.Directory.Ldap.NETStandard#171]
I can't find in the documentation how to manage wheter the provided account is:
DISABLED,
PASSWORD EXPIRED,
BLOCKED,
NEED PASSWORD CHANGE

and so on

Thanks

**Comment by dsbenghe** [comment]
This library is purely an LDAP client library. It doesn't have any specific functionality for a particular LDAP protocol compatible server (like Active Directory). You can layer that yourself on top of the library i.e. read the attribute which stores the data you are looking for like any other attribute.
