### ISSUE TITLE
Performance issue with Following Referrals

### ISSUE THREAD

**Issue by danielDevelops** [dsbenghe/Novell.Directory.Ldap.NETStandard#176]
Version 3.x seems to have a long delay in following referrals.  This was not present in version 2.x but shows up in 3.x.  The perf when making a simple CN query goes from sub 100 MS in version 2.x but goes up to 3 seconds in 3.x when following referrals.

**Comment by dsbenghe** [comment]
Close this until proven that there is really an issue.
