### ISSUE TITLE
Performance issue while connecting from linux container

### ISSUE THREAD

**Issue by kalyan-raman** [dsbenghe/Novell.Directory.Ldap.NETStandard#180]
Environment : Docker Desktop for Windows - Linux container
Novell.Directory.Ldap.NETStandard version: 3.6.0
.NET 5
Docker image - aspnet:5.0-1

I am trying to connect to ldap server over unsecured channel using SaslDigestMd5Request.  The connect and bind methods are taking over 2 seconds.

How to address this. Can the connection be registered as a singleton

**Comment by se** [comment]
Did you try to install your certificate in your Docker image?

**Comment by se** [comment]
@dsbenghe probably you need to close this 🖖
