### ISSUE TITLE
Getting "Invalid Address" error even after passing correct LDAP address.

### ISSUE THREAD

**Issue by munish29sharma** [dsbenghe/Novell.Directory.Ldap.NETStandard#20]
i am using below code, passing LDAP address in ldapHost but getting error "Invalid Address- Input string was not in a correct format." 

               {
                    var cn = new LdapConnection()
                    cn.Connect("LDAP://OU=XYZ,DC=XYZ,DC=XY", 389);
                    cn.Bind(userName, password);
                }

please help if i am doing something wrong.
is there any special format required in Hostname ?

Note:- i have changed the actual names in ldap.

**Comment by dsbenghe** [comment]
Hostname is what usually people understand by hostname - DNS resolvable name; on windows, netbios names work too. Take also a look to the tests and samples.
