### ISSUE TITLE
The code in AddUserToGroup not working with Active Directory

### ISSUE THREAD

**Issue by aniljain100** [dsbenghe/Novell.Directory.Ldap.NETStandard#21]
Hi,

I have copied the sample code from the file to add a user to a group frm the below link but its throwing error: 
Novell.Directory.Ldap.NETStandard/original_samples/Samples/AddUserToGroup.cs

The error is: "00000057: LdapErr: DSID-0C090CE0, comment: Error in attribute conversion operation, data 0, v2580\0"

Below are the values used:
int ldapPort = LdapConnection.DEFAULT_PORT;
int ldapVersion = LdapConnection.Ldap_V3;
bool status = false;
LdapConnection conn = new LdapConnection();
String ldapHost = "adcndazr01.wwt-cnd.local";
String loginDN = "WWT-CND\\mlekkala";
String password = "password";
System.String userDN = "CN=Ksmith,CN=Users,DC=wwt-cnd,DC=local";
System.String groupDN = "CN=myDeltaGroupTest,CN=Users,DC=wwt-cnd,DC=local";

Can you please help me?

Thanks
Anil Jain

**Comment by dsbenghe** [comment]
Active Directory is always a little bit special when working with it via LDAP protocol - so the samples may work or not.

I always recommend looking in java space when talking about Active Directory and LDAP - heaps better chances to find reasonable docs/samples. And the java ldap code samples should be very easy to translate to use this library.

For example, this may help you with your problem - https://stackoverflow.com/questions/21147625/java-ldap-add-group-to-user-issue-error-code-53-will-not-perform

**Comment by h3smith** [comment]
Also note you must be connected via TLS/SSL to perform many actions in AD/LDAP.

**Comment by aniljain100** [comment]
Hi @dsbenghe and Harold Smith,

Thanks for your response. I posted the question only after seeing the below link you mentioned.

[LDAP Add group to user issue](https://stackoverflow.com/questions/21147625/java-ldap-add-group-to-user-issue-error-code-53-will-not-perform)

Thanks
Anil Jain

**Comment by aniljain100** [comment]
Hi,

Solved the issue and it turned out to be able to add only user to a group and cannot add a group name to a user.

Thanks
Anil Jain
