### ISSUE TITLE
Empty password in BindAsync does not throw exception

### ISSUE THREAD

**Issue by Ainyru** [dsbenghe/Novell.Directory.Ldap.NETStandard#227]
Using 4.0.0 version, method BindAsync throws exception when password is wrong except when password passed as "".

**Comment by klasen** [comment]
This is working correctly. With an empty password, you are asking the server to perform an Unauthenticated Simple Bind: https://www.rfc-editor.org/rfc/rfc4513#section-5.1.2. 
Duplicate of #229
