### ISSUE TITLE
Bind() with exclamation mark in the password

### ISSUE THREAD

**Issue by CreaturePrime** [dsbenghe/Novell.Directory.Ldap.NETStandard#228]
When attempting to Bind an LDAP Connection, the credentials will fail to validate if the password has an exclamation mark.

    string ldapPwd = "MyPassword!";
    LdapConnection LdapConn = new LdapConnection();
    LdapConn.Connect(ldapServer, ldapPort);
    LdapConn.Bind(ldapUser, ldapPwd);
 
I've tried various methods of escaping the special character, but I haven't been able to find a workaround.
Thanks in advance

**Comment by dsbenghe** [comment]
Added a test with a user with a password with many special chars (including !) that is green.
