### ISSUE TITLE
Get all the LDAP entry attribute names in active directory

### ISSUE THREAD

**Issue by aniljain100** [dsbenghe/Novell.Directory.Ldap.NETStandard#23]
Is there a way in C# I could get the list of all attribute names in active directory using LDAP.

Thanks
Anil Jain

**Comment by dsbenghe** [comment]
You can search for an entry in active directory with the usual ldap way using wildcards to specify all attributes and you will get all the attributes for that entry.

Microsoft should also have some docs with all the attributes - this one looks potentially ok - https://msdn.microsoft.com/en-us/library/ms675085(v=vs.85).aspx

**Comment by aniljain100** [comment]
I am sorry I think I am not clear with my question. In the below code I am hard coding the attributes for adding a new entry:



```
           LdapAttributeSet attributeSet = new LdapAttributeSet();
            attributeSet.Add(new LdapAttribute("givenname",
                   "Anilsnew1"));
            attributeSet.Add(new LdapAttribute("sn", "Anilsnew1"));
            attributeSet.Add(new LdapAttribute("telephonenumber", "1 801 555 1212"));
            attributeSet.Add(new LdapAttribute("mail", "anilsnew1@own.com"));
            attributeSet.Add(new LdapAttribute("userpassword", "Anilsnew"))
            string dn = "cn=" + user.UserName + "," + _containerName;
            sstring dn = Guid.NewGuid().ToString();
            newEntry = new LdapEntry(dn, attributeSet);
            LdapConnection conn = new LdapConnection();
            conn.Connect(_ldapHost, _ldapPort);
            conn.Bind(_loginDN, _password);
            LdapEntry ldapEntry = new LdapEntry();
            conn.Add(newEntry);
```


I dont want to hardcode the attribute name. How would I do it?

Thanks

**Comment by aniljain100** [comment]
I found this code but not sure about schemaDN:


```
LdapSchema schema = _ldapConnection.FetchSchema(schemaDN);

IEnumerator attributeSchemas = schema.LDAPSchema.AttributeSchemas
```

**Comment by dsbenghe** [comment]
Not really clear for me what do you want to achieve. Ok, you could read the schema dynamically, but you still need a place where to specify what is the attribute name for "first name" or "last name" e.g.

{ "firstname", "givenname"},
{"lastname", "sn"} ...

The standard object classes "person", "organizationalPerson", "inetOrgPerson" and others are supposed to be the same for all the ldap servers and you can find their schema in the RFCs.

**Comment by aniljain100** [comment]
Ok. While adding a new ldap entry in Active directory we add attributes like the below code in .NET:

          
```
LdapAttributeSet attributeSet = new LdapAttributeSet();
 attributeSet.Add(new LdapAttribute("givenname", "Anil Kumar"));
 attributeSet.Add(new LdapAttribute("sn", "Anil Kumar"));
attributeSet.Add(new LdapAttribute("telephonenumber", "1 801 555 1212"));
attributeSet.Add(new LdapAttribute("mail", "anilkumar@own.com"));
attributeSet.Add(new LdapAttribute("userpassword", "Anilkumar"))
```
I dont want to hardcode the attribute names like "givenname", "mail", "userPrincipalName" etc. There are 32 user level attributes I believe.

In other words I want to retrieve the following attribute names list

```
objectSid 
sAMAccountName
accountExpires
whenChanged 
countryCode 
memberOf 
uSNCreated 
cn 
sAMAccountType
sn 
primaryGroupID
userAccountCont
whenCreated 
lastLogoff 
pwdLastSet 
objectGUID 
givenName 
dSCorePropagati
objectClass 
uSNChanged 
name 
displayName 
lastLogon 
logonCount 
mail
distinguishedNa
badPasswordTime
badPwdCount 
userPrincipalName
codePage 
instanceType 
objectCategory
```
The user would send these attributes and its values in key value pair as input.
I will validate the attribute names sent by the user and add the values to the attribute set.

Thanks

**Comment by dsbenghe** [comment]
maybe this will help - it looks that this is what you want

https://serverfault.com/questions/598853/view-all-possible-attributes-of-an-objectclass-for-ldap

you will need to translate the command lines to api calls.
