### ISSUE TITLE
How work sample attribute compare ?

### ISSUE THREAD

**Issue by iamkisly** [dsbenghe/Novell.Directory.Ldap.NETStandard#24]
Hello! How work sample [VerifyPassword](https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/master/original_samples/Samples/VerifyPassword.cs) ? For example, my password is "xsWxPoF0 * 2%", I enter a known bad password and it's successful. What does it mean ?

**Comment by iamkisly** [comment]
+1

**Comment by dsbenghe** [comment]
The sample is the original one - not sure if it works or not.

You can read more about how to verify password on this issue - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/14

**Comment by dsbenghe** [comment]
Please reopen if you something is still unclear about how to verify password.
