### ISSUE TITLE
How to display get all username list from Active directory?

### ISSUE THREAD

**Issue by Iamguy84** [dsbenghe/Novell.Directory.Ldap.NETStandard#25]
Hi Novell,

I am using Netcore. I tried to follow your sample code:
using (var cn = new LdapConnection())
{
..............
	cn.Connect("<<hostname>>", 389);
	cn.Bind("<<userdn>>", "<<userpassword>>");
..............
}
And it goes well 😊.

Now I am looking for search username list from active directory. 
Is there any sample code of it?

I am waiting for your response.

Thanks in advance.

Regards,
Adnan Salahuddin

**Comment by dsbenghe** [comment]
This is done same way using any ldap client library - nothing specific to this library - you do a search with the right ldap filter.

This sample may give to the main idea - Novell.Directory.Ldap.NETStandard/original_samples/Samples/List.cs

**Comment by Iamguy84** [comment]
Thank you for your guidelines
