### ISSUE TITLE
Provide Xml comments file with nuget package

### ISSUE THREAD

**Issue by maximpashuk** [dsbenghe/Novell.Directory.Ldap.NETStandard#26]
nuget package for novell.directory.ldap.netstandard version 2.3.7 contains only .dll file and no .xml file with api documentation.

Dll enough for compilation.
Xml comments file is useful then developing in Visual Studio, since in shows annotations on classes, methods, etc.
So now I used to frequently switch between GitHub\VisualStudio - to read method annotations and write code.

So please add .xml comments file in nuget package, this is common best-practice.

**Comment by dsbenghe** [comment]
done - it will be included with the next release.
