### ISSUE TITLE
Implement async methods

### ISSUE THREAD

**Issue by maximpashuk** [dsbenghe/Novell.Directory.Ldap.NETStandard#27]
Version 2.3.7 used

For now all kind of API is totally synchronous, no Task<T> used.
Underlying .net core asynchronous methods decorated with .WaitAndUnwrap() and .ResultAndUnwrap()

API should be refactored to support methods returning Task (ConnectAsync, BindAsync, etc).

**Comment by dsbenghe** [comment]
While async is obviously very nice, it is a reasonable effort to implement it as to do it right needs to be implemented all the way down. Just to fake it at the api level here and there so it looks async it is wasted effort.

Happy to take pull requests, but probably time will be better invested in implementing authentication with client certificates or/and gssapi before even thinking about async.

**Comment by maximpashuk** [comment]
I agree that client certificates and gssapi take priority over this. So just keep it as backlog.

**Comment by dsbenghe** [comment]
4.0.0-alpha1 has an initial implementation of async

**Comment by dsbenghe** [comment]
Implemented in 4.x

**Comment by dsbenghe** [comment]
Closed as it is implemented in 4.x
