### ISSUE TITLE
Is there a way to get the Attributes of a user using LdapSearchResults

### ISSUE THREAD

**Issue by nigelgrannum** [dsbenghe/Novell.Directory.Ldap.NETStandard#29]
I can query AD and get a list of LdapSearchResults but when I try to get attributes I only get DN.  Is there a way to get other attributes, such as sAMAcountName, without having to bind to the user?

**Comment by dsbenghe** [comment]
I think by default you should get all the attributes which are set unless you specify in the search call that you want just a subset of them.

Take a look at the tests or at the original samples.

**Comment by nigelgrannum** [comment]
The typesOnly argument to LdapConnection.Search need to be set to false.
