### ISSUE TITLE
Use byte[] instead of sbyte[] for 'blob' abstraction

### ISSUE THREAD

**Issue by maximpashuk** [dsbenghe/Novell.Directory.Ldap.NETStandard#30]
I can see in API many usings of type sbyte[].

For example, ```LdapAttribute.ByteValue``` returns sbyte[].
I know I can do sbyte[] to byte[] transition and back using ```SupportClass.ToByteArray``` or ```SupportClass.ToSByteArray```

I just can't find any reasons for such design.
Probably this is historical reasons (java code port?).

Many base .NET API (BitConverter, MemoryStream, Encoding) uses byte[] as parameter and not sbyte[].
In .net world is more naturally to use byte[] as 'blob' abstraction.
In blob nobody cares about the 'sign' of a byte, so you can safely use byte[] instead of sbyte[] everywhere.

So please refactor this library to use byte[] for blobs.

**Comment by dsbenghe** [comment]
Yeah; this is due to the conversion from java to C#; in java a byte is signed in .net is unsigned. It is one of the weirdness of this code base - another one is heaps of methods are virtual (and they don't need to be) just because in java methods are by default virtual.

**Comment by dsbenghe** [comment]
Fixed starting with 3.0.0-beta.
