### ISSUE TITLE
Unable to change user's password (Active Directory)

### ISSUE THREAD

**Issue by gerwim** [dsbenghe/Novell.Directory.Ldap.NETStandard#31]
Hi guys,

First, thank you for porting the code over to .Net core!

I'm having some issues with changing the user's password using the LDAP modify methods. I receive one of the following errors, depends which route I take:
1) Binding as a domain admin and using LdapModification.REPLACE:
`Unwilling To Perform (53) Unwilling To Perform
LdapException: Server Message: 0000001F: SvcErr: DSID-031A12D2, problem 5003 (WILL_NOT_PERFORM), data 0`
2) Binding as the user itself and using LdapModification.DELETE and LdapModification.ADD:
`Constraint Violation (19) Constraint Violation
LdapException: Server Message: 00002081: AtrErr: DSID-03190FA0, #1:
	0: 00002081: DSID-03190FA0, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9005a (unicodePwd)`

## Code exempts for both routes:
1): Binding as a domain admin:
```c#
string UserToChange = "CN=myUser,OU=InSome,OU=OU,DC=domain,DC=local"
LdapAttribute attribute = new LdapAttribute("unicodePwd", "\"myNewStrongPassword\"");
LdapModification modification = new LdapModification(LdapModification.REPLACE, attribute);

 _connection.Modify(UserToChange, modification);
```

2) Binding as the user:
```c#
string UserToChange = "CN=myUser,OU=InSome,OU=OU,DC=domain,DC=local"
LdapModification[]` modifications = new LdapModification[2];
LdapAttribute deletePassword = new LdapAttribute("unicodePwd", "\"myOldPassword\"");
modifications[0] = new LdapModification(LdapModification.DELETE, deletePassword);
LdapAttribute addPassword = new LdapAttribute("unicodePwd", "\"myNewStrongPassword\"");
modifications[1] = new LdapModification(LdapModification.ADD, addPassword);

 _connection.Modify(UserToChange, modifications);
```

Things I have checked and tried:
1) Convert the password to Unicode (UTF16-LE) byte array and then convert to a base64 string using the code below
```c#
string password = "\"myNewStrongPassword\"";
byte[] encodedBytes = Encoding.Unicode.GetBytes(password);
string encodedTxt = Convert.ToBase64String(encodedBytes);
```

2) Connect with SSL (this is the only way to perform actions on the `unicodePwd` field
3) Read various implementations on the web, most of them are Java and PHP which I found
4) The password `myNewStrongPassword` is valid against the AD password policies

If anyone has any idea or could point me in the right direction, that would be great! :-)

**Comment by gerwim** [comment]
I managed to fix this by doing the following:

Instead of:
```c#
string password = "\"myNewStrongPassword\"";
byte[] encodedBytes = Encoding.Unicode.GetBytes(password);
string encodedTxt = Convert.ToBase64String(encodedBytes);
```

Convert it to sbyte (and drop the string and base64 encoding):

```c#
string password = "\"myNewStrongPassword\"";
sbyte[] encodedBytes = SupportClass.ToSByteArray(Encoding.Unicode.GetBytes(password));
LdapAttribute deletePassword = new LdapAttribute("unicodePwd", encodedBytes);
```

**Comment by maxis777** [comment]
Hi guys,

I steel have the same issue and cannot fix it...
I connect to LDPA using SSL and after i can get infos from AD create OU etc
But when i try to create a user i receive the same error as described in this topic.

> 0000001F: SvcErr: DSID-031A1254, problem 5003 (WILL_NOT_PERFORM), data 0

Creation of user without password working well...

There are the code that i use to connect to AD:
1) Connection

```
LdapConnection conn = new LdapConnection();
 conn.SecureSocketLayer = true;
conn.UserDefinedServerCertValidationDelegate += (sender, certificate, chain, sslPolicyErrors) => true; 
conn.Connect(this.ADExtHost, 636);
conn.Bind(LdapConnection.Ldap_V3, this.ADExtLogin, this.ADExtPassword);
```

2) Adding user to AD
```
LdapAttributeSet attributeSet = new LdapAttributeSet();
attributeSet.Add(new LdapAttribute("userPrincipalName", username + "_" + domain + "@external.local"));
attributeSet.Add(new LdapAttribute("mail", user.Email));
attributeSet.Add(new LdapAttribute("objectClass", new string[] { "user", "organizationalPerson", "person", "top" }));
attributeSet.Add(new LdapAttribute("name", user.Email));

sbyte[] encodedBytes = SupportClass.ToSByteArray(Encoding.Unicode.GetBytes(password));
attributeSet.Add(new LdapAttribute("unicodePwd", encodedBytes));

attributeSet.Add(new LdapAttribute("userAccountControl", "544"));

 //DN of the entry to be added
string dn = $"cn={user.Email}," + container;
LdapEntry newEntry = new LdapEntry(dn, attributeSet); 

//Add the entry to the directory
connection.Add(newEntry);
```

**Comment by leo9223** [comment]
For me this is working

`var bytes = Encoding.ASCII.GetBytes(newPassword);
var sbytes = bytes.Select(b => Convert.ToSByte(b)).ToArray();
LdapAttribute attribute = new LdapAttribute("userPassword", sbytes);`

**Comment by xrkolovos** [comment]
This Code didn't work. 
```C#
var bytes = Encoding.ASCII.GetBytes(newPassword);
var sbytes = bytes.Select(b => Convert.ToSByte(b)).ToArray();
LdapAttribute attribute = new LdapAttribute("userPassword", sbytes);
```
I get error "No Such Attribute"
```
00002085: AtrErr: DSID-031525C6, #1:
	0: 00002085: DSID-031525C6, problem 1001 (NO_ATTRIBUTE_OR_VAL), data 0, Att 23 (userPassword):len 12
```

With This Code 
```C#
LdapModification[] modifications = new LdapModification[2];
//
sbyte[] encodedBytesOldPass = SupportClass.ToSByteArray(Encoding.Unicode.GetBytes("\"" + oldPassword + "\""));
LdapAttribute deletePassword = new LdapAttribute("unicodePwd", encodedBytesOldPass);
modifications[0] = new LdapModification(LdapModification.DELETE, deletePassword);
//
sbyte[] encodedBytesNewPass = SupportClass.ToSByteArray(Encoding.Unicode.GetBytes("\"" + newPassword + "\""));
LdapAttribute addPassword = new LdapAttribute("unicodePwd", encodedBytesNewPass);
modifications[1] = new LdapModification(LdapModification.ADD, addPassword);

connection.Modify(UserToChange, modifications);
```
 Still doen't work. I get "Constraint Violation"
```
0000052D: AtrErr: DSID-03190FD6, #1:
	0: 0000052D: DSID-03190FD6, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9005a (unicodePwd)
```

**Comment by gokulm** [comment]
Enclosing the password within double quotes is IMPORTANT. 

string password = "\"myNewStrongPassword\"";
byte[] encodedBytes = Encoding.Unicode.GetBytes(password);
string encodedTxt = Convert.ToBase64String(encodedBytes);

**Comment by leo9223** [comment]
so my code works with enclosing password with double qoutes

**Comment by USFbobFL** [comment]
> I managed to fix this by doing the following:
> 
> Instead of:
> 
> ```cs
> string password = "\"myNewStrongPassword\"";
> byte[] encodedBytes = Encoding.Unicode.GetBytes(password);
> string encodedTxt = Convert.ToBase64String(encodedBytes);
> ```
> 
> Convert it to sbyte (and drop the string and base64 encoding):
> 
> ```cs
> string password = "\"myNewStrongPassword\"";
> sbyte[] encodedBytes = SupportClass.ToSByteArray(Encoding.Unicode.GetBytes(password));
> LdapAttribute deletePassword = new LdapAttribute("unicodePwd", encodedBytes);
> ```

thanks, but still getting this:
Unwilling To Perform 0000001F: SvcErr: DSID-031A12D2, problem 5003 (WILL_NOT_PERFORM), data 0 �

**Comment by USFbobFL** [comment]
> For me this is working
> 
> `var bytes = Encoding.ASCII.GetBytes(newPassword);`
> 
> `var sbytes = bytes.Select(b => Convert.ToSByte(b)).ToArray();`
> 
> `LdapAttribute attribute = new LdapAttribute("userPassword", sbytes);`

While this method does not generate an error, it also does not update the password.

**Comment by ysakiyev** [comment]
> I managed to fix this by doing the following:
> 
> Instead of:
> 
> ```cs
> string password = "\"myNewStrongPassword\"";
> byte[] encodedBytes = Encoding.Unicode.GetBytes(password);
> string encodedTxt = Convert.ToBase64String(encodedBytes);
> ```
> 
> Convert it to sbyte (and drop the string and base64 encoding):
> 
> ```cs
> string password = "\"myNewStrongPassword\"";
> sbyte[] encodedBytes = SupportClass.ToSByteArray(Encoding.Unicode.GetBytes(password));
> LdapAttribute deletePassword = new LdapAttribute("unicodePwd", encodedBytes);
> ```

1. SupportClass does not have ToSByteArray
2. LdapAttribute ctor doesn't take sbyte[] as 2nd arg

giving it string throws Exception unwilling to perform.
So how it works  now? version 3.0.3 
Thanks

**Comment by DAVID0375** [comment]
Hi there
on my case using the above code I'm facing the same issue :(
About the user.Dn is like this --> “cn= firstname.lastname,o=organizationunit,c=us”

Thanks in Advance

**Comment by Legolas53723** [comment]
Hi there
on my case using the above code I'm facing the same issue :(
About the user.Dn is like this --> “cn= firstname.lastname,o=organizationunit,c=us”

Thanks in Advance

**Comment by bbteam17** [comment]
this is working for me . I tested .
` conn.Modify(user.Dn, new LdapModification(LdapModification.Replace, new LdapAttribute("unicodePwd", Encoding.Unicode.GetBytes($@"""{password}"""))));`

**Comment by cjag74** [comment]
Did below and it work!

First, install SSL cert in AD then reboot AD server
https://www.manageengine.com/products/active-directory-audit/kb/how-to/how-to-install-ssl-certificates-in-active-directory.html

Second, verify LDAPS connection

After a certificate is installed, follow these steps to verify that LDAPS is enabled:
Start the Active Directory Administration Tool (Ldp.exe).
On the Connection menu, click Connect.
Type the name of the domain controller to which you want to connect.
Type 636 as the port number.
Click OK.
RootDSE information should print in the right pane, indicating a successful connection.

Third, used code below

 public async Task<IActionResult> OnPostSubmit()
 {
            
	    var ldapConnection = new LdapConnection(new LdapDirectoryIdentifier("abc.com", 636, true, false));
            ldapConnection.AuthType = AuthType.Basic;
            ldapConnection.SessionOptions.VerifyServerCertificate = new VerifyServerCertificateCallback((con, cer) => true);
            ldapConnection.SessionOptions.SecureSocketLayer = true;
            ldapConnection.Credential = new NetworkCredential("abc\\abcadmin", "AdminPassw0rd");
            ldapConnection.Bind();

            // Set the new password for the user
            string password = "NewPassw0rd";
            byte[] encodedPassword = Encoding.Unicode.GetBytes($@"""{password}""");

            DirectoryAttributeModification dirmod = new DirectoryAttributeModification();
            dirmod.Operation = DirectoryAttributeOperation.Replace;
            dirmod.Name = "unicodePwd";
            dirmod.Add(encodedPassword);

            ModifyRequest request = new ModifyRequest("CN=UserToChangeFor,CN=Users,DC=abc,DC=com", dirmod);

            // Execute the request to reset the password
            ModifyResponse response = (ModifyResponse)ldapConnection.SendRequest(request);

            return Page();

}
