### ISSUE TITLE
xamarin.android Bind issue

### ISSUE THREAD

**Issue by zuimengaitianya** [dsbenghe/Novell.Directory.Ldap.NETStandard#32]
In the xamarin.android platform, part of the mailAccount and PassWord using the Bind () method error,but in windows platform is good.why?

sorry,this is  error
 Novell.Directory.Ldap.LdapException: Invalid Credentials

**Comment by dsbenghe** [comment]
Let me get this right - you have the exact same piece of code connecting to the same ldap server - you run it on Windows and it works, but you get "Invalid Credentials" on xamarin.android?

As I'm not using xamarin.android I can comment on or debug this issue. In theory it should work (as mentioned here - https://docs.microsoft.com/en-us/dotnet/standard/net-standard ).

You will need to debug it by yourself. Easiest option is if your ldap server supports some tracing/debug logging to see what you received on ldap side for both cases. The other one is to dump the ldap bind request sent by the library on both Windows and android before is transmitted over the network and compare the two.

**Comment by dsbenghe** [comment]
Closing this as there are no updates after 1.5 months.
