### ISSUE TITLE
Get user details

### ISSUE THREAD

**Issue by thedumbtechguy** [dsbenghe/Novell.Directory.Ldap.NETStandard#33]
Hello,

So I have been able to login using the library, but try as I may, I can't craft the proper `dn` to retrieve the user as it seems to use the fullname as `cn`.
Is there a way to do this easier without searching? Searching seems to hang visual studio btw.
I am basically trying to retrieve a list of groups that the user belongs to to use as claims.

Thank you.

**Comment by dsbenghe** [comment]
AFAIK you can do a read with the dn or a search.

Regarding search hanging Visual Studio - I don't think is that hard to hang VS :).

The functional tests are running heaps of searches without hanging. If you can reproduce the hanging while running command line (or make a test reproducing the hanging and send a pull request with the test), I'm happy to take a look.
