### ISSUE TITLE
how to retrieve password expiration for a user

### ISSUE THREAD

**Issue by guigui43** [dsbenghe/Novell.Directory.Ldap.NETStandard#35]

**Comment by dsbenghe** [comment]
That is specific to every ldap server. As far as I know there isn't a standard ldap attribute for password expiration, but a particular ldap server may have one - e.g. OpenDJ for example has attributes whose names are starting with "ds" which are specific to OpenDJ and it has one for password expiration.

**Comment by guigui43** [comment]
For Active Directory ? Which property ?

**Comment by dsbenghe** [comment]
Check the docs or google it.
