### ISSUE TITLE
Not Populating Computer Objects that are Members of a Group

### ISSUE THREAD

**Issue by RFBennet** [dsbenghe/Novell.Directory.Ldap.NETStandard#36]
I'm using this library with .NET CORE 2.0.0 to pull information out of Active Directory. However, I'm running into an issue.

When grabbing the list of objects that are members of a Group, it doesn't seem to return Computer account objects (just User and Group objects).

What I mean is, if "**GroupXYZ**" has these as members:
**JimmyUser
SallyUser
Computer212
Computer010
GroupABC
GroupG21**

When I query the Group, I'll get 2 Users and 2 Groups back just fine. However, the 2 Computer account objects wouldn't show up in the return (and nothing blows up or anything).

`string[] membersArray = attributeSet.getAttribute("member")?.StringValueArray;`

If I use the _Active Directory Users and Computers_ console, I can see that there are indeed a number of Computer objects that are members of the Group. But I'm not able to get them returned by grabbing the "member" attribute on the Group.

Thanks!

**Comment by dsbenghe** [comment]
To confirm if there is an issue with this library or not you should try to use an LDAP browser kind of application (there are plenty), connect to AD to see if you can see what you are looking for. 

Active Directory Users and Computers console is for sure not using the LDAP protocol for communication.

It may be that is just one of the special cases of AD working a little bit different over the ldap protocol - so this should be reduced to finding that "special" way of reading that data you are looking for from AD.

**Comment by RFBennet** [comment]
Sorry it took so long to get back to this (other projects needing to be moved forward).

I had a bug in my code that was throwing off my testing. So it now appears that the library does indeed pull in computer objects that are a member of a domain group.

However, only if there is not a huge number of members in the group.

If the number is too large, the call doesn't seem to return anything. I used "LDAP Admin" to take a peek at things, and it seems as if instead of the expected "member" property, it changes to something like "member;range=0-1499".

Am I missing some other method or something that I should be calling for groups with large memberships? Or is this something that needs to be addressed in the library?

Thanks!

**Comment by dsbenghe** [comment]
You need to use search with range as described here - https://msdn.microsoft.com/en-us/library/Aa367017?f=255&MSPPError=-2147217396 

The library doesn't have any specific support for this - but you can easily implement it on top of it as far as I see.
