### ISSUE TITLE
Unable to control LDAP connection timeout

### ISSUE THREAD

**Issue by jfharvie** [dsbenghe/Novell.Directory.Ldap.NETStandard#37]
The LdapConnection class does not provide a way to control the timeout. I attempted to do so by changing the Constraints.TimeLimit value but it does not have any effect on the initial connection.

On Windows I'm getting a timeout value of just over 3 seconds but on Linux under Mono 4.8.1 the time out value is over 2 minutes.

This can be improved with a small change to AsyncExtensions.cs in the function WaitAndUnwrap() if you passed in a timeout value (ideally from a new variable in the LdapConnection) and called task.Wait() with that value.

**Comment by dsbenghe** [comment]
This is a good idea; happy to take a pull request for this change.

**Comment by dsbenghe** [comment]
pull request merged
