### ISSUE TITLE
How rewrite this ldap query of password verification?

### ISSUE THREAD

**Issue by Jenan** [dsbenghe/Novell.Directory.Ldap.NETStandard#38]
Hello,

how can I rewrite this password verification?

https://stackoverflow.com/questions/8949501/why-does-active-directory-validate-last-password/8951536#8951536

Lot of object are different from full .NET Framework. :) 

Thank you.

**Comment by dsbenghe** [comment]
The landing page of the github project has a clear example of how to validate the credentials.
