### ISSUE TITLE
Search method async?

### ISSUE THREAD

**Issue by doc** [dsbenghe/Novell.Directory.Ldap.NETStandard#4]
Hi There. Firstly, thanks so much for your working in getting this running on .net core! I'm looking to use your project in an aspnet core project and am having some challenges performing a search from a web api controller. I'm essentially getting 0 search results back from the search. If I add a Thread.wait(100) after the search I invariably get search results ... am I using search incorrectly? Is there a sync method that I'm missing?

Again, thanks for your work!

Mark

**Comment by dsbenghe** [comment]
Search has a couple of versions: some of them are async (not in the .net style, but nevertheless there are async) - the ones returning LdapSearchQueue, some of them are sync (in the implementation there are using the async version and block waiting for the response) - the ones returning LdapSearchResults.

I just pushed a test for the sync version of Search and is working fine - take a look at it.

If you still have problems send a repro or even better send a pull request with a failing test.

**Comment by dsbenghe** [comment]
Close this as in this case no news should be good news :)

**Comment by MaitreDede** [comment]
Hi @dsbenghe ,
I have the same kind of issue. I am running a simple sync search that should returns results (checked with an ldap explorer tool) with debugger attached :

                var users = con.Search(searchBase, scope, searchFilter, attrs, typesOnly);
                int count = users.Count;
                Console.WriteLine(count);

When executing this code directly, `count` is 0. When executing step by step, `count` is 1.
`searchBase` is my users group "ou=People", `scope` is 1, `searchFilter` is "(uid=myusername)", `attrs` is string[0], `typesOnly` is false.

Instead of trying to understand why it fails, is it possible to make a "task async" extension method that hides all your "async" complexity so the method signature would be `Task<LdapSearchResults> SearchAsync(string @base, int scope, string filter, string[] attrs, bool typesOnly)` ?

Thanks.

**Comment by MaitreDede** [comment]
Sample "async" extension method :

        public static Task<IList<LdapEntry>> SearchAsync(this ILdapConnection con, string @base, int scope, string filter, string[] attrs, bool typesOnly)
        {
            var queue = con.Search(@base, scope, filter, attrs, typesOnly, (LdapSearchQueue)null);
            //TaskCompletionSource<LdapSearchResults> tcs = new TaskCompletionSource<LdapSearchResults>();

            return Task.Factory.StartNew<IList<LdapEntry>>(() =>
            {
                List<LdapEntry> lst = new List<LdapEntry>();
                LdapMessage message;
                int status = LdapException.OTHER;
                while ((message = queue.getResponse()) != null)
                {

                    // OPTION 1: the message is a search result reference
                    if (message is LdapSearchResultReference)
                    {
                        // Not following referrals to keep things simple
                        String[] urls = ((LdapSearchResultReference)message).Referrals;
                        Console.WriteLine("Search result references:");
                        for (int i = 0; i < urls.Length; i++)
                            Console.WriteLine(urls[i]);
                    }

                    // OPTION 2:the message is a search result
                    else if (message is LdapSearchResult)
                    {
                        // Get the object name
                        LdapEntry entry = ((LdapSearchResult)message).Entry;
                        lst.Add(entry);
                    }

                    // OPTION 3: The message is a search response
                    else
                    {
                        LdapResponse response = (LdapResponse)message;
                        status = response.ResultCode;

                        // the return code is Ldap success
                        if (status == LdapException.SUCCESS)
                        {
                            //Console.WriteLine("Asynchronous search succeeded.");
                        }

                        // the return code is referral exception
                        else if (status == LdapException.REFERRAL)
                        {
                            String[] urls = ((LdapResponse)message).Referrals;
                            Console.WriteLine("Referrals:");
                            for (int i = 0; i < urls.Length; i++)
                                Console.WriteLine(urls[i]);
                        }
                        else
                        {
                            Console.WriteLine("Asynchronous search failed.");
                            Console.WriteLine(response.ErrorMessage);
                        }

                        // Server should send back a control irrespective of the 
                        // status of the search request
                        LdapControl[] controls = response.Controls;
                        if (controls != null)
                        {

                            // Theoritically we could have multiple controls returned
                            for (int i = 0; i < controls.Length; i++)
                            {

                                // We are looking for the LdapSortResponse Control class - the control
                                // sent back in response to LdapSortControl
                                if (controls[i] is LdapSortResponse)
                                {

                                    Console.WriteLine("Received Ldap Sort Control fromserver");

                                    // We must have an error code and maybe a string identifying
                                    // erring attribute in the response control.  Get these.
                                    String bad = ((LdapSortResponse)controls[i]).FailedAttribute;
                                    int result = ((LdapSortResponse)controls[i]).ResultCode;

                                    // Print out error ccode (0 if no error) and any returned
                                    // attribute
                                    Console.WriteLine("Error code: " + result);
                                    if (bad != null)
                                        Console.WriteLine("Offending " + "attribute: " + bad);
                                    else
                                        Console.WriteLine("No offending " + "attribute " + "returned");
                                }
                            }
                        }
                    }
                }
                if (status == LdapException.SUCCESS)
                {
                    return lst.AsReadOnly();
                }
                else
                {
                    //TODO error message
                    throw new LdapException();
                }
            });
        }

**Comment by dsbenghe** [comment]
Count doesn't return "correctly" because is not blocking and doesn't wait to get the results and is returning whatever is available at that moment. It is true that this behavior is not the most expected one :) - and it may have an easy fix.

It will return correctly after calling hasMore - which is blocking (e.g. wait for the result).

Probably will be useful to make the "async" methods match the .net style. And even make the sync methods to return IEnumerable as will make the usage easier. Happy to take pull requests :)
