### ISSUE TITLE
Compatibility Issue with .NET Core 2.0

### ISSUE THREAD

**Issue by joellacas** [dsbenghe/Novell.Directory.Ldap.NETStandard#40]
Is it possible that this library is not compatible with .NET core 2.0 ?

**Comment by dsbenghe** [comment]
What error do you get? The library is built on .NET Standard 1.3 - nothing to do with any of the .net core versions - and it should run fine on any runtime compatible with .NET Standard 1.3, which includes the .net core versions.

**Comment by smuthiya** [comment]
If consumer/client application of this library is moving to .NET Core 2.0 then now .NET Core 2.0 has a built in support for DirectoryServices. 
Following namespace should help you (mostly)-
https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices?view=netcore-2.0

**Comment by Li-ReDBox** [comment]
@smuthiya from what I have investigated, DirectoryServices only runs on Windows. There is no implementation of [System.DirectoryServices.Protocols](https://github.com/dotnet/corefx/issues/24843) yet.
