### ISSUE TITLE
How to connect without domain?

### ISSUE THREAD

**Issue by balkarov** [dsbenghe/Novell.Directory.Ldap.NETStandard#43]
Hello!

Thank you for your library.
My code:
```
using (var conn = new LdapConnection())
{
    conn.Connect("192.168.55.111", 389);
    conn.Bind("balkarov@some.office", "password");
}
```

This is work. But could I check password without domain? For example
`conn.Bind("balkarov", "password");`

PS: in c I can use ContextType.Domain

I try this
`conn.Bind("CN=balkarov,OU=Company,DC=Some,DC=Office", "password");`
but this does not work

**Comment by dsbenghe** [comment]
I'm not using the library with AD (other people are), but AFAIK you need to specify the domain in a way or the other - e.g. windows style (using \ or @) or ldap style (correctly crafted DN syntax).

**Comment by balkarov** [comment]
There is I can login without @domain in System.DirectoryServices.AccountManagement.PrincipalContext

**Comment by balkarov** [comment]
@dsbenghe look on my code for DirectoryServices:
```
using (var pc = new PrincipalContext(ContextType.Domain, $"{ldapSettings.Server}:{ldapSettings.Port}", $"{ldapSettings.TreeRoot}", ContextOptions.Negotiate))
            {
                return pc.ValidateCredentials(username, password);
            }
```

username is simple without domain, @ and etc. for example balkarov. 
But if I use your library then I must use balkarov@some.office

**Comment by OskarKlintrot** [comment]
Where are not using the domain either:
https://github.com/Certaincy/Intranet/blob/master/src/Intranet.Web.Authentication/Services/LdapAuthenticationService.cs#L31-L88 (abandoned project, we moved it to a private repo now). However, we have one user that we bind first (same one every time) and then we search for the user that wants to login and bind that user next. Unfortunately I have no clue if it would work for us to bind the user first or if there is any differences between the users.

**Comment by balkarov** [comment]
@OskarKlintrot thanks, but how login without this "one user that we bind first"?

**Comment by OskarKlintrot** [comment]
Our flow is like this:
 1. [Connect](https://github.com/Certaincy/Intranet/blob/master/src/Intranet.Web.Authentication/Services/LdapAuthenticationService.cs#L42)
 2. [Bind App User](https://github.com/Certaincy/Intranet/blob/master/src/Intranet.Web.Authentication/Services/LdapAuthenticationService.cs#L43)
 3. [Search for Username](https://github.com/Certaincy/Intranet/blob/master/src/Intranet.Web.Authentication/Services/LdapAuthenticationService.cs#L45-L56)
 4. [Get User](https://github.com/Certaincy/Intranet/blob/master/src/Intranet.Web.Authentication/Services/LdapAuthenticationService.cs#L58)
 5. [Bind User from step 4](https://github.com/Certaincy/Intranet/blob/master/src/Intranet.Web.Authentication/Services/LdapAuthenticationService.cs#L61)
 6. [If  we could bind, user is verified](https://github.com/Certaincy/Intranet/blob/master/src/Intranet.Web.Authentication/Services/LdapAuthenticationService.cs#L62-L72)

We never specify the domain, in fact we [strip it away if the user has added it](https://github.com/Certaincy/Intranet/blob/master/src/Intranet.Web.Authentication/Services/LdapAuthenticationService.cs#L37-L40).

**Comment by OskarKlintrot** [comment]
Do you have any error messages? Have you tried with `ReferralFollowing = true` and `ReferralFollowing = false`?

**Comment by balkarov** [comment]
@OskarKlintrot thank you very much for your help, but ReferralFollowing does not work for me
my code:
```
using (var conn = new LdapConnection())
            {
                conn.Connect("192.168.55.111", 389);
                conn.Constraints.ReferralFollowing = false; // and I tried true
                conn.Bind("balkarov", "mypass");
                var isBound = conn.Bound;
            }
```


I get error `Invalid credentials`

But if I change to this code then all work.
```
using (var conn = new LdapConnection())
            {
                conn.Connect("192.168.55.111", 389);
                conn.Bind("balkarov@some.office", "mypass");
                var isBound = conn.Bound;
            }
```

Do you understand?

**Comment by OskarKlintrot** [comment]
I just realized that we are actually signing in with the username from LDAP, we are just using the input to search for it. I don't know if that has the domain attached to it or not and I have no way to find out either anytime soon. It could be that the user we bind first is "unique" and has access to search in our domain. I have never worked on that side of LDAP so I'm just guessing.

Do you have multiple domains or can you just attach the domain prior to binding it?

**Comment by balkarov** [comment]
I have only one domain. 
I told that it work in DirectoryServices PrincipalContext.
But my case does not work in Novell.Directory.Ldap.NETStandard

**Comment by OskarKlintrot** [comment]
Why don't you just append you domain to the username then?

**Comment by balkarov** [comment]
I have user without domain.
Do you mean parse tree root and append this for username?

**Comment by OskarKlintrot** [comment]
What I mean is that if the user inputs his or hers `username` and you know the `domain` (since you only have one) why don't you just concatenate them together (`username + domain`)?

**Comment by balkarov** [comment]
Because I do not know domain.
I know this info:
- Server
- Port
- Username
- Password
- TreeRoot (for example: `OU=Company,DC=Some,DC=Office`

**Comment by OskarKlintrot** [comment]
Can't you ask some sysadmin for the domain name? I don't think I can help you any more than this, let's hope someone with better knowledge about this project and LDAP shows up!

**Comment by balkarov** [comment]
Look. 
We have something panel setting for our platform. 
Admin user (not ldap user) can settings in this platform. 
Platform has LDAP settings. 
Admin user (not ldap user) can settings LDAP fo himself company. 
He can input: username, password, server, port and tree root. 
And after click save -> get LDAP user list (usernames).
After any user (from ldap) can login to our platforms via his username and password via LDAP.
Do you understand?

**Comment by balkarov** [comment]
@dsbenghe hello!
Could you tell me please? How can I connect to server with this uri format `LDAP://dc1.corp.domain.com/OU=Service Accounts,OU=Corp Objects,DC=corp,DC=domain,DC=com` use your library?

**Comment by dsbenghe** [comment]
The code you initially posted 

using (var conn = new LdapConnection())
{
    conn.Connect("192.168.55.111", 389);
    conn.Bind("CN=someusername,OU=Service Accounts,OU=Corp Objects,DC=corp,DC=domain,DC=com", "password");
}

will work as long as the DN & password combination is correct - so you need to make sure is correct. You will get a specific error (think Invalid credentials) if the dn/password combination is incorrect. Do you get some other error?

**Comment by balkarov** [comment]
This code does not work
```
using (var conn = new LdapConnection())
{
                conn.Connect("192.168.55.111", 389);
                conn.Bind("CN=balkarov,OU=Company,DC=Some,DC=Office", "password");
}
```

I get error Invalid credential.
All data is correct.

**Comment by OskarKlintrot** [comment]
If I remember correct you should get more error messages than `Invalid Credentials`. That one shows up like all the time but there is more info if you look for it, don't remember if it's on a different property or inner exception though... I got `Invalid Credentials` even though my actual error was a connection timeout.

**Comment by balkarov** [comment]
@OskarKlintrot 
LdapMessageError: "80090308: LdapErr: DSID-0C090400, comment: AcceptSecurityContext error, data 52e, v1db1\0"

**Comment by balkarov** [comment]
@OskarKlintrot I found my problem. 
CN - is not username. CN - is name and surname

**Comment by OskarKlintrot** [comment]
Glad you at least got it up and running! 👍

**Comment by trsprogeekatlarge** [comment]
@balkarov
Sorry to show up late to the party. Years of dealing with LDAP for AAA in various apps leads me to confirm what @OskarKlintrot has suggested. The most commonly used method I've seen across a wide variety of LDAP-enabled cross-platform apps is to use a service account to do the initial bind, search for the user (either by samAccountName or mail attribute), then use the password provided at login to attempt another bind to LDAP with the login form password and the "found" user DN. Exception/error handling at this stage is always the "fun" part. 

Hope it helps to at least know you aren't alone, this is how we've done it for ages in other frameworks that aren't so tightly windows integrated. I never expected to be doing it in .NET to talk to AD! :)

**Comment by dsbenghe** [comment]
Everything seems fine - so I'm closing this.

**Comment by PriyaDave** [comment]
I need to implement AD authentication in .NET Core and it is going to be hosted in Linux environment.
I tried System.DirectoryServices to implement the same but seems not working.
After  going through a number of blogs, it seems Novell.Directory.Ldap.NetStandard is  helpful to achieve what I want.
I tried following code: 
 ```
using (var connection = new LdapConnection())
            {
                connection.Connect(hostName, LdapConnection.DEFAULT_PORT);
                connection.Bind("priya.dave@xyz.co.nz", "password");
                if (connection.Bound)
                    return true;
            }
```

I am not able to connect. I am getting exception at connection.Connect(). It shows "None of the discovered or specified addresses match the socket address family".  What can be the issue?

Thanks,
Priya

**Comment by Pelice** [comment]
@PriyaDave Try to set in the new connection the security layer. I use this this library in linux docker and for me works fine

```
//Set the connection type (secure / unsecure)
var connection = new LdapConnection() { SecureSocketLayer = _useSSL };

//Connect function will create a socket connection to the server - Port 389 for insecure and 3269 for secure   
ldapConnection.Connect(_serverName, _serverPort);
```
