### ISSUE TITLE
[Test] How config

### ISSUE THREAD

**Issue by lillo42** [dsbenghe/Novell.Directory.Ldap.NETStandard#44]
I am trying run test but always fail, because cannot connect to server(localhost)

How can I configure LDAP on my PC to run test?

I am using Windows

**Comment by dsbenghe** [comment]
Look in the travis ci build file - .travis.yml - there is the setup for openldap on linux; most of the setup deals with the ssl configuration.

You could setup openldap on Windows; or you could run opendj which is easier to setup on Windows for ssl connection.

**Comment by lillo42** [comment]
I create a VM with linux,

I installed all package on .travis.yml, but when I run this code on terminal:  

`ldapwhoami -H ldap://localhost:4389 -D "cn=root,dc=example,dc=com" -w password `

Show this message:
`ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)`

Have any idea what can be ?

**Comment by dsbenghe** [comment]
before_script contains the setup; 

looks that in your case there is no ldap server running on 4389; default port is 389 - but the tests are running on 4389 - on of the lines of the script starts the openldap server on 4389 and 4636

**Comment by lillo42** [comment]
Thank,
