### ISSUE TITLE
MacOS High Sierra with Mono

### ISSUE THREAD

**Issue by danielDevelops** [dsbenghe/Novell.Directory.Ldap.NETStandard#46]
I have found a bug that might be with the Mono Framework in that when calling the new SslStream on line 594 in Connection.cs the RemoteCertificateValidationCallback is never called.  I am not able to reproduce the error when compiling to .net Core on MacOS but it is reproducible with Mono.

This was working before I upgraded to High Sierra but now is causing the issue.  From what i can see it fails during the WaitAndUnwrap method.

**Comment by dsbenghe** [comment]
Don't really matter that much if it works on Mono or not :) - so unless someone else cares that much about this to take a look at this ...
