### ISSUE TITLE
Sample code showing return of large recordset?

### ISSUE THREAD

**Issue by RFBennet** [dsbenghe/Novell.Directory.Ldap.NETStandard#47]
First off, thanks for the library! It's been really useful in the .NET Core project I'm currently working on.

Secondly, would it be possible to get a new sample added that shows how to (quickly/efficiently) return a large number of records in an LDAP search?

I can get 1000 records no problem of course, but I'm struggling with getting 80,000+ records from Active Directory (when it does work, it seems to take forever to process). What am I missing? I'm still fairly new to C# and .NET; so maybe it's something simple...? A sample code snippet would be extremely helpful.

        public void LargeRecordSearchTest()
        {
            string searchBase = "MySearchbaseInfo";
            bool searchTypes = false;
            int resultsCount = 0;
            string searchFilter = "(&(objectCategory=computer)(operatingSystem=Windows*))";
            string[] searchAttributes = {
                    "distinguishedName",
                    "operatingSystem"
                };
            ConnectToLDAP();
            LdapSearchConstraints ldapSearchConstraints = _ldapConnection.SearchConstraints;
            //ldapSearchConstraints.MaxResults = 0;
            LdapSearchResults ldapSearchResults = _ldapConnection.Search(
                searchBase,
                LdapConnection.SCOPE_SUB,
                searchFilter,
                searchAttributes,
                searchTypes,
                ldapSearchConstraints
            );
            while (ldapSearchResults.hasMore())
            {
                resultsCount++;
            }
            //_logger.LogInformation($"Number of results returned: {resultsCount}");
            DisconnectFromLDAP();
        }

**Comment by dsbenghe** [comment]
Maybe this will help - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/71

**Comment by dsbenghe** [comment]
version >= 3.5.1 have SimplePagedResultsControl implemented and there are sample and helpers implemented to use SimplePagedResultsControl and VLV control for doing paged searches - see the tests for examples.
