### ISSUE TITLE
Password is not set for created Active Directory user using Novell.Directory.Ldap.NETStandard C#

### ISSUE THREAD

**Issue by michaelrajece** [dsbenghe/Novell.Directory.Ldap.NETStandard#51]
I used the following code to create a new user in active directory. From this, the new user is created in active directory without any error. But, I could not work with that new user using its password, here i am set the password using "**userPassword**" attribute.
Is this correct way to set password for user using "**userPassword**" attribute or please guide me the correct workflow to achieve this?
                       
 ```
LdapAttributeSet attributeSet = new LdapAttributeSet();
attributeSet.Add(new LdapAttribute("objectclass", "user"));
attributeSet.Add(new LdapAttribute("sAMAccountName", "myuser"));
attributeSet.Add(new LdapAttribute("userPRincipalName", "myuser"));
attributeSet.Add(new LdapAttribute("userAccountControl", (66080).ToString()));
attributeSet.Add(new LdapAttribute("userPassword", "mypassword"));

string dn = "CN=myuser,CN=Users,DC=mydomain,DC=com";
LdapEntry newEntry = new LdapEntry(dn, attributeSet);

LdapConnection ldapConn = new LdapConnection();
ldapConn.Connect(ldapHost, 369);
ldapConn.Bind(loginDN, password);
ldapConn.Add(newEntry);
```

**Comment by dsbenghe** [comment]
As mentioned before on other issues, AD when used via LDAP is special :) - take a look at this issue https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/31 and probably you will find out the solution to your problem.

**Comment by michaelrajece** [comment]
@dsbenghe Thanks for your update. I have changed my code as per your solution like below.
```
string mynewpassword = "\"mickpass@123\"";
sbyte[] encodedBytes = SupportClass.ToSByteArray(Encoding.Unicode.GetBytes(mynewpassword));
attributeSet.Add(new LdapAttribute("unicodePwd", encodedBytes));
```

But, still I am getting the following error.
{LdapException: Unwilling To Perform (53) Unwilling To Perform
LdapException: Server Message: 0000001F: SvcErr: DSID-031A12D2, problem 5003 (WILL_NOT_PERFORM), data 0

What I am doing wrong in this? I will need to Connect with SSL? (this is the only way to perform actions on the unicodePwd field) if need then how can I make that SSL LDAP connection in C# code?

**Comment by dsbenghe** [comment]
yes, you need ssl; see tests & samples for how to do that.

**Comment by michaelrajece** [comment]
@dsbenghe Where can I get sample for ssl connection? Please give any working samples.

**Comment by viggykuppu** [comment]
@michaelrajece Here is some sample code for connecting to AD over SSL:

`		    cn.SecureSocketLayer = true;
		    cn.UserDefinedServerCertValidationDelegate += (sender, certificate, chain, sslPolicyErrors) => true;
            cn.Connect(_hostname, LdapConnection.DEFAULT_SSL_PORT);
            cn.Bind(LdapConnection.Ldap_V3, _username, _password);`

**Comment by michaelrajece** [comment]
@viggykuppu Thank you very much. Your code done the tricks for me.
