### ISSUE TITLE
 Novell.Directory.Ldap.NETStandard : Issue while getting 'objectGUID' value from Active Directory

### ISSUE THREAD

**Issue by yogirp** [dsbenghe/Novell.Directory.Ldap.NETStandard#52]
I am using .Net Core 2.0 and Novell.Directory.Ldap.NETStandard 2.3.8 and used the following code to get User resource attributes from active directory. 
I am getting values for all attributes except for objectGUID where I am getting some garbage value.

LdapEntry userEntry = ldapConn.Read(dn);
LdapAttribute uid = userEntry?.getAttribute("objectGUID");

Output:
{LdapAttribute: {type='objectGUID', value='�� ��E�1�Ѕv'}}

There are no issues if I use LDAP as a backend entity.

When I used below code to get Guid, I got following error.
new Guid(SupportClass.ToByteArray(userEntry.getAttribute("objectGuid").ByteValue)).ToString()

Error:
'new Guid(SupportClass.ToByteArray(userEntry.getAttribute("objectGuid").ByteValue)).ToString()' threw an exception of type 'System.ArgumentException'
"Byte array for GUID must be exactly 16 bytes long.\r\nParameter name: b"

**Comment by moskvitin** [comment]
Did you try to use `objectGUID` instead `objectGuid`?

**Comment by yogirp** [comment]
https://github.com/moskvitin Yes. I tried using objectGUID but got same result.

**Comment by moskvitin** [comment]
@yogirp i have same code as you describe:
`new Guid(SupportClass.ToByteArray(attributeSet.getAttribute("objectGUID").ByteValue)).ToString()` and it works well. Configuration such as yours: .Net Core 2.0 and Novell.Directory.Ldap.NETStandard 2.3.8. May be you can check this value by ADExplorer?

**Comment by yogirp** [comment]
@moskvitin  Thank you. It's working.
