### ISSUE TITLE
get exception when Get Usergroups from ActiveDirectory after Login

### ISSUE THREAD

**Issue by coolrz** [dsbenghe/Novell.Directory.Ldap.NETStandard#53]
i follow the https://nicolas.guelpa.me/blog/2017/02/15/dotnet-core-ldap-authentication.html link to write the code below, the LDAP connection is ok, but when call the  var user = lsc.next(); it will throw exception. My purpose is to get user group according to one user
/***************** code  start**************/
conn.connect,..

 string searchFilter = "(&(objectClass =user)(objectClass=person)(sAMAccountName={0}))";
            LdapSearchResults lsc = conn.Search("DC=svc,DC=accenture,DC=com",
                                                LdapConnection.SCOPE_SUB,
                                                string.Format(searchFilter, userName),
                                                new[] { MemberOfAttribute, DisplayNameAttribute, SAMAccountNameAttribute },                                                
                                                false);
            try
            {
                var user = lsc.next();
                if (user != null)
                {
                    if (conn.Bound)
                    {
                        var temp = new AppUser
                        {
                            DisplayName = user.getAttribute(DisplayNameAttribute).StringValue,
                            Username = user.getAttribute(SAMAccountNameAttribute).StringValue,
                            IsAdmin = user.getAttribute(MemberOfAttribute).StringValueArray.Contains("admin")
                        };
                    }
                }
            }
            catch (LdapException ex)
            {

            }

/*********** code end *******************
exception below
![capture](https://user-images.githubusercontent.com/9249080/37203985-898e62e4-23ca-11e8-801d-8919900ad982.PNG)

**Comment by dodegaard** [comment]
I get the same thing

**Comment by Sebosek** [comment]
Please provide an exception, we're using this library with Samba4 as well as with Active Directory without problems...

**Comment by dsbenghe** [comment]
Can you send a pull request with a failing test.

**Comment by mstum** [comment]
The message says that it's getting a Referral, I wonder if referrals aren't being followed?

Wondering if this would work when setting up the LdapConnection:

```
var conn = new LdapConnection();
var constraints = conn.Constraints;
constraints.ReferralFollowing = true;
conn.Constraints = constraints;
// now do the rest as before to search etc...
```

LdapConstraints.ReferralFollowing defaults to false:

```
/// <summary>
///     Specifies whether referrals are followed automatically or if
///     referrals throw an LdapReferralException.
///     Referrals of any type other than to an Ldap server (for example, a
///     referral URL other than ldap://something) are ignored on automatic
///     referral following.
///     The default is false.
/// </summary>
```

**Comment by Zubastic** [comment]
> 
> 
> The message says that it's getting a Referral, I wonder if referrals aren't being followed?
> 
> Wondering if this would work when setting up the LdapConnection:
> 
> ```
> var conn = new LdapConnection();
> var constraints = conn.Constraints;
> constraints.ReferralFollowing = true;
> conn.Constraints = constraints;
> // now do the rest as before to search etc...
> ```
> 
> LdapConstraints.ReferralFollowing defaults to false:
> 
> ```
> /// <summary>
> ///     Specifies whether referrals are followed automatically or if
> ///     referrals throw an LdapReferralException.
> ///     Referrals of any type other than to an Ldap server (for example, a
> ///     referral URL other than ldap://something) are ignored on automatic
> ///     referral following.
> ///     The default is false.
> /// </summary>
> ```

But ReferralFollowing is not working at all:
                                if (cons.ReferralFollowing)
                                {
                                    // referralConn = conn.chaseReferral(queue, cons, msg, refs, 0, true, referralConn);
                                }
                                else
                                {
                                    references.Add(refs);
                                    referenceCount++;
                                }

So no any chasing...

**Comment by dsbenghe** [comment]
this should work now due to the changes done here - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/pull/93
