### ISSUE TITLE
Does this library support LdapConnection with current process credentials instead of connection arguments?

### ISSUE THREAD

**Issue by AKrasheninnikov** [dsbenghe/Novell.Directory.Ldap.NETStandard#54]
If you try to avoid storing admin credentials, can you still use this library to connect and perform admin operations by leveraging process credentials implicitly?

**Comment by AKrasheninnikov** [comment]
Like this? 
var cc = CredentialCache.DefaultNetworkCredentials;
_ldap.Connect(_ldapHost, _ldapPort);
_ldap.Bind(LdapConnection.Ldap_V3, cc.UserName, cc.Password);

**Comment by dsbenghe** [comment]
no, it doesn't.
