### ISSUE TITLE
Documentation claims LdapConnection.Search is synchronous, but it isn't.

### ISSUE THREAD

**Issue by SuperSkippy** [dsbenghe/Novell.Directory.Ldap.NETStandard#55]
e.g.

```
LdapSearchResults queue = cn.Search("ou=base,dc=example,dc=com", LdapConnection.SCOPE_BASE, null, null, false);
Console.WriteLine(queue.Count);
Thread.Sleep(1000);
Console.WriteLine(queue.Count);
```

will give different numbers for the count. The intellisense docs say:

Synchronously performs the search specified by the parameters.

Is there any way of waiting until it is done before returning?

**Comment by SuperSkippy** [comment]
What I'm doing is `queue.HasMore()` before I use it which seems to force it to be up-to-date.

**Comment by dsbenghe** [comment]
See here - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/4
