### ISSUE TITLE
Start_TLS TLS_REQCERT=allow?

### ISSUE THREAD

**Issue by patrickgardella** [dsbenghe/Novell.Directory.Ldap.NETStandard#56]
I'm working to connect to an Azure Active Directory Domain Services test configuration. It uses a self signed SSL cert for use with TLS, but because of the way AADDS works, the hostname is not the same as the domain name, so the cert doesn't match the domain name, and fails.

On the command line, I can make this work using `ldapsearch` by setting `TLS_REQCERT=allow`. According to the [help](https://linux.die.net/man/5/ldap.conf), that means:

> The server certificate is requested. If no certificate is provided, the session proceeds normally. If a bad certificate is provided, it will be ignored and the session proceeds normally.

Is there a way to tell StartTLS to ignore a bad certificate like this? I couldn't find anything in the source.

**Comment by dsbenghe** [comment]
this should work  - this is how the tests are running.

ldapConnection.UserDefinedServerCertValidationDelegate += (sender, certificate, chain, errors) => true;

**Comment by patrickgardella** [comment]
Perfect! Thank you so much. It worked great.
