### ISSUE TITLE
Change Password not taking effect

### ISSUE THREAD

**Issue by gokulm** [dsbenghe/Novell.Directory.Ldap.NETStandard#57]
Any idea on this https://stackoverflow.com/questions/48285865/change-password-not-taking-effect-with-novell-ldap-modification-for-asp-net-core

**Comment by dsbenghe** [comment]
See here https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/31 and here https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/51 for previous discussion and solutions
