### ISSUE TITLE
C# Novell.Directory.Ldap .NETSTandard VLV control :  LDAP search works fine in debug mode always but not in real time 

### ISSUE THREAD

**Issue by yogirp** [dsbenghe/Novell.Directory.Ldap.NETStandard#59]
I am using Novell.Directory.Ldap.NETStandard 2.3.8 and .Net Core 2.0 for my application.

When I do search using below code in debug mode, I got the correct results/response always. But when I do it without debugging, search returns different results. 
Observation: If I put some delays in while loop to get next entry, it works fine as well in real time. 

LdapVirtualListControl vlv = null;
LdapSortKey[] keys = new LdapSortKey[1];
keys[0] = new LdapSortKey("******");
sort = new LdapSortControl(keys, true);
vlv = new LdapVirtualListControl(1, 0, 10, 0);

LdapSearchConstraints searchConstraints = new LdapSearchConstraints();
searchConstraints.BatchSize = 1;
searchConstraints.MaxResults = 10000;

List<LdapControl> controlArr = new List<LdapControl>();
controlArr.Add(sort);
controlArr.Add(vlv);
searchConstraints.setControls(controlArr.ToArray());

LdapSearchResults lsc = ldapConnection.Search("---SearchBaseDn----",
LdapConnection.SCOPE_SUB,
"---filter----",
"---attributes to retrieve----",
false,
searchConstraints);

while (lsc.hasMore())
{
	LdapEntry nextEntry = null;
	try
	{
		nextEntry = lsc.next();
	}
	catch (LdapException e)
	{
		// Exception is thrown, go for next entry
		continue;
	}
}

**Comment by dsbenghe** [comment]
Can you send a pull request with a failing test?

**Comment by prisznitz** [comment]
same here. framework 4.6.1

**Comment by dsbenghe** [comment]
I added a test using VLV - I haven't seen any problem while running it in a loop for a while.

If you still see a problem please create a PR with a failing test. You can use the docker container prepared (which is also used to run the unit tests) via run-opendj.bat and add a test to the current functional tests.
