### ISSUE TITLE
System.NullReferenceException when trying to connect via SSL

### ISSUE THREAD

**Issue by saschakloeppner** [dsbenghe/Novell.Directory.Ldap.NETStandard#6]
I get this error when trying to connect to an LDAP server  with ssl enabled.
I am using the Version 2.3.5 provided by nuget.

System.NullReferenceException wurde nicht behandelt.
Message: Ein Ausnahmefehler des Typs "System.NullReferenceException" ist in System.Private.CoreLib.ni.dll aufgetreten.
Zusätzliche Informationen: Object reference not set to an instance of an object.

**Comment by dsbenghe** [comment]
Is that SSL (e.g. ldapConnection.SecureSocketLayer = true) or TLS (StartTls/StopTls)? The SSL implementation is quite simple (don't see where it can break) and works fine for me. TLS is a little bit trickier.

I wrote some tests for SSL and TLS. No issues with SSL, but the TLS seems to fail sometimes (StopTls seems to throw NullReference sometimes in my stress test suite when running on 50 threads simultaneous in Debug mode, but not Release).

Can you post more details: the stack trace or a repro or even better a pull request with a failing test?! On what os/runtime are you running?

**Comment by saschakloeppner** [comment]
It is ldapConnection.SecureSocketLayer = true
When I clone the git repository and connect via LDAPS using your test project everything works well.
But using the version provided by nuget I am unable to bind via SSL.
I am running on windows.

**Comment by saschakloeppner** [comment]
OK it was my fault :-(
I connected to the server before setting SSL = true.

```
Connection = new Novell.Directory.Ldap.LdapConnection();
Connection.Connect(server, port);
Connection.SecureSocketLayer = useSsl;
Connection.Bind(userDn, password);
```

So never mind xD
