### ISSUE TITLE
Supports or will support connection and search to the Directory's Global Catalog

### ISSUE THREAD

**Issue by VikoBastidas** [dsbenghe/Novell.Directory.Ldap.NETStandard#64]
In the .NET Framework System.DirectoryServices, you could connect to a server in two ways, LDAP:// ServerNameOrIP or GC://ServerNameOrIP. The second way allowed to make searches in the global catalog or the entire domain forest.

**Comment by mstum** [comment]
Try connecting to LDAP:// ServerNameOrIP on Port 3268 (or Port 3269 for LDAPS) - that's the Global Catalog port, I think the GC:// syntax is just a shortcut to set the port.

**Comment by VikoBastidas** [comment]
Thanks for the advice Michael, it works.
