### ISSUE TITLE
Bind through GSSAPI

### ISSUE THREAD

**Issue by watanabekiyoshi** [dsbenghe/Novell.Directory.Ldap.NETStandard#7]
I see there is SaslBindProperties, however it's a readonly property and initialized with null.

Is the library support binding of "GSSAPI"

Thanks in advance
w.k.

**Comment by dsbenghe** [comment]
No - it doesn't. 

There are some traces in the code about Sasl - but these are coming from the Java translation when Sasl wasn't really implemented. In the meantime, the Java version implemented some of Sasl mechanisms - but just some of the easy choices and not GSSAPI.
