### ISSUE TITLE
LdapSearchConstraints MaxResults and BatchSize not working

### ISSUE THREAD

**Issue by sjzamora86** [dsbenghe/Novell.Directory.Ldap.NETStandard#71]
I'm having Size Exceeded error even I added the constraints

LdapSearchConstraints cons = new LdapSearchConstraints();
            cons.ReferralFollowing = true;
            cons.MaxResults = 0;
            cons.BatchSize = 5;

Novell.Directory.Ldap.LdapException
  HResult=0x80131500
  Message=Sizelimit Exceeded
  Source=Novell.Directory.Ldap.NETStandard
  StackTrace:
   at Novell.Directory.Ldap.LdapResponse.chkResultCode()
   at Novell.Directory.Ldap.LdapSearchResults.next()

**Comment by fcastell** [comment]
I have the same problem. After some tests, I foud that the error is throw by the LDAP server not the library.
If, like me, the LDAP Server is Active Directory, the default limit is 1000. To solve this problem you have 2 solutions : change the limit inside Active Directory or use search query inside your program to fiter the result.
For me it is not possible to change the limit so I use the second solution. My solution is base from this post (https://forum.glpi-project.org/viewtopic.php?id=29888) :
`

            for (char letterOne = 'a'; letterOne <= 'z'; letterOne++)
            {
                for (char letterTwo = 'a'; letterTwo <= 'z'; letterTwo++)
                {
                    using (LdapConnection ldapConn = GetConnection())
                    {
                        LdapSearchConstraints cons = new LdapSearchConstraints
                        {
                            MaxResults = 0,
                            ReferralFollowing = true
                        };

                        var searchBase = "_yoursearchbase_";
                        string filter = $"(&(objectClass=user)(DisplayName={letterOne}{letterTwo}*))";
                        var search = ldapConn.Search(searchBase, LdapConnection.SCOPE_SUB, filter, null, false, cons);

                        while (search.hasMore())
                        {
                            var nextEntry = search.next();
                            var attributes = nextEntry.getAttributeSet();

                             ..........
                        }

                        ldapConn.Disconnect();
                        ldapConn.Dispose();
                    }
                }
            }
`

**Comment by sjzamora86** [comment]
Thanks for the reply. I will have an issue by changing the filter so I end up using LdapVirtualListControl controller and it is working as expected. I just followed what is in here:
[https://stackoverflow.com/questions/48805577/how-to-do-a-paged-search-on-an-ldap-server-with-lots-of-users](url)

**Comment by dsbenghe** [comment]
I think all ldap servers have a size limit on what are returning when searching and that is the error you are getting.
