### ISSUE TITLE
Novell Ldap Connection unit test

### ISSUE THREAD

**Issue by sjzamora86** [dsbenghe/Novell.Directory.Ldap.NETStandard#73]
Hello, 
We are using this library but we are having a hard time to unit test our service that instantiate LdapConnection object. 

Any help will be much appreciated

**Comment by dsbenghe** [comment]
See here - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/12 - and report if you still have issues - in this case, a concrete example will be welcome.

**Comment by sjzamora86** [comment]
Thank you @dsbenghe
