### ISSUE TITLE
Complete novice...

### ISSUE THREAD

**Issue by ASKemp** [dsbenghe/Novell.Directory.Ldap.NETStandard#75]
Can anyone point me to some pages, guides etc. that show how to use this in an existing .net core application.

I've added the nugget package. What is the bare minimum I need to do to query an AD with a given user id/password and check that it's correct, i.e. for a bare bones authentication.

Many thanks.

**Comment by dsbenghe** [comment]
Bare minimum sample code is on the main page of the project - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard

You can take a look at the tests too. Or at the old samples and adapt them slightly.
