### ISSUE TITLE
Unable to create user with password (Active Directory)

### ISSUE THREAD

**Issue by maxis777** [dsbenghe/Novell.Directory.Ldap.NETStandard#77]
Hi guys,

I still have the same issue as #31  and cannot fix it...
I connect to LDPA using SSL and after i can get infos from AD create OU etc
But when i try to create a user i receive the same error as described in this topic.

> 0000001F: SvcErr: DSID-031A1254, problem 5003 (WILL_NOT_PERFORM), data 0

Creation of user without password working well...

Thanks

There are the code that i use to connect to AD:
1) Connection

```
LdapConnection conn = new LdapConnection();
 conn.SecureSocketLayer = true;
conn.UserDefinedServerCertValidationDelegate += (sender, certificate, chain, sslPolicyErrors) => true; 
conn.Connect(this.ADExtHost, 636);
conn.Bind(LdapConnection.Ldap_V3, this.ADExtLogin, this.ADExtPassword);
```

2) Adding user to AD
```
LdapAttributeSet attributeSet = new LdapAttributeSet();
attributeSet.Add(new LdapAttribute("userPrincipalName", username + "_" + domain + "@external.local"));
attributeSet.Add(new LdapAttribute("mail", user.Email));
attributeSet.Add(new LdapAttribute("objectClass", new string[] { "user", "organizationalPerson", "person", "top" }));
attributeSet.Add(new LdapAttribute("name", user.Email));

sbyte[] encodedBytes = SupportClass.ToSByteArray(Encoding.Unicode.GetBytes(password));
attributeSet.Add(new LdapAttribute("unicodePwd", encodedBytes));

attributeSet.Add(new LdapAttribute("userAccountControl", "544"));

 //DN of the entry to be added
string dn = $"cn={user.Email}," + container;
LdapEntry newEntry = new LdapEntry(dn, attributeSet); 

//Add the entry to the directory
connection.Add(newEntry);
```

**Comment by dsbenghe** [comment]
Sorry, but AD has its quirks when used via Ldap. Nothing to do with this library. Look at the other issues about AD or generally search for the other people experience in doing this operation via Ldap (any other library not just this one) and probably you will find the solution.

**Comment by dsbenghe** [comment]
I will keep it open for a while to be more visible, maybe someone else can help you.

**Comment by mharrisn** [comment]
Experiencing the same issue. While troubleshooting the issue, I found that the account does get created successfully if the password attribute is removed. Since "userAccountControl" is 544 the password is not required. I added the user account, then I tried both an LDAPConnection.ADD and LDAPConnection.REPLACE for unicodePwd and got the same 5003 unwilling error.

**Comment by maxis777** [comment]
So there are no way to create a new user in Active Directory with password ?? :(
How people does it in .NET CORE ?
