### ISSUE TITLE
Use strict ipv6 connection.

### ISSUE THREAD

**Issue by LexMelnikov** [dsbenghe/Novell.Directory.Ldap.NETStandard#78]
The problem is similar to https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/67.

GetHostAddressesAsync returns ipv4 and ipv6 addresses. Our local server works only with ipv6 addresses with HAProxy. I want to explicitly indicate which address type to use.

Also this line works fine only with ipv4, but not with ipv6 colons.
https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/72230ea4f6686062ed74f6a8ae9ab91524ffbead/src/Novell.Directory.Ldap.NETStandard/LdapConnection.cs#L913

**Comment by gertgjoka** [comment]
How come this is not yet taken care of? Basically with the port parsing code above, there is no way to use an IPv6 address at all. Why does it say on version 3 it supports IPv6?

**Comment by dsbenghe** [comment]
Since 3.6.x new feature was introduced to be able to filter the ip addresses used for connecting e.g.

```          
var options = new LdapConnectionOptions()
	.ConfigureIpAddressFilter(ip => ip.AddressFamily == AddressFamily.InterNetworkV6)
using var ldapConnection = new LdapConnection(options);
ldapConnection.Connect(...)
```

In addition, the feature which was triggering the parsing (which don't think had too much usage) is not supported anymore.
