### ISSUE TITLE
Get Usergroups from ActiveDirectory after Login

### ISSUE THREAD

**Issue by MoiraG** [dsbenghe/Novell.Directory.Ldap.NETStandard#8]
Hello,

is it possible to get all groups from a specific user?
Something like:

```c#
using (var cn = new LdapConnection())

 {
     // connect
     cn.Connect("domain", 389);
    // bind with an username and password
     // this how you can verify the password of an user
     cn.Bind("user", "pw");
     var usergroups = cn.GetUserGroups();
 }
```

I have tested the samples from this project, but i didn't find a solution.

Thanks for your work on this library.

**Comment by dsbenghe** [comment]
It is not that simple. When using a Ldap client library on top of Active Directory you need to use the ldap way of doing the things. There aren't any shortcuts like when you will use a MS specific Active Directory client library.

Basically you need:
- connect and bind with any user with permission to read entries
- do a search for the user/users you want to find info about
- decode the ldap entry/entries returned (e.g. memberOf attribute contains the groups - see also this issue - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/1)

If you want to find more info about how to do it you will have more luck if you are looking for Java samples as most of the C# samples will use the MS specific way and not using the LDAP way.

See here for something which achieves that in Java:
- http://stackoverflow.com/questions/570466/java-ldap-determine-if-user-in-a-given-group
- https://blogs.msdn.microsoft.com/alextch/2007/06/18/sample-java-application-that-retrieves-group-membership-of-an-active-directory-user-account/ - this one is using AD specific attribute tokenGroups.

**Comment by dsbenghe** [comment]
Someone write a blog post with complete code which is reading also the groups - https://nicolas.guelpa.me/blog/2017/02/15/dotnet-core-ldap-authentication.html

**Comment by gfoidl** [comment]
For a prototype application I've written this code for getting all groups (recursively) for the user.

```
private readonly LdapConnection _ldapConnection;

// ...

public IEnumerable<string> GetGroupsForUser(string userName)
{
    _ldapConnection.Bind(_config["ldapAdmin"], _config["ldapPassword"]);

    var groups       = new Stack<string>();
    var uniqueGroups = new HashSet<string>();

    foreach (string group in this.GetGroupsForUserCore(userName))
        groups.Push(group);

    while (groups.Count > 0)
    {
        string group = groups.Pop();
        if (uniqueGroups.Add(group))
            yield return group;

        foreach (string parentGroup in this.GetGroupsForUserCore(group))
            groups.Push(parentGroup);
    }
}

private IEnumerable<string> GetGroupsForUserCore(string user)
{
    LdapSearchQueue searchQueue = _ldapConnection.Search(
        _config["searchBase"],
        LdapConnection.SCOPE_SUB,
        $"(sAMAccountName={user})",
        new string[] { "cn", "memberOf" },
        false,
        null as LdapSearchQueue);

    LdapMessage message;
    while ((message = searchQueue.getResponse()) != null)
    {
        if (message is LdapSearchResult searchResult)
        {
            LdapEntry entry = searchResult.Entry;
            foreach (string value in HandleEntry(entry))
                yield return value;
        }
        else
            continue;
    }

    IEnumerable<string> HandleEntry(LdapEntry entry)
    {
        LdapAttribute attr = entry.getAttribute("memberOf");

        if (attr == null) yield break;

        foreach (string value in attr.StringValueArray)
        {
            string groupName = GetGroup(value);
            yield return groupName;
        }
    }

    string GetGroup(string value)
    {
        Match match = Regex.Match(value, "^CN=([^,]*)");

        if (!match.Success) return null;

        return match.Groups[1].Value;
    }
}
```
