### ISSUE TITLE
Is there a way to mock Bound?

### ISSUE THREAD

**Issue by RetroMechanics** [dsbenghe/Novell.Directory.Ldap.NETStandard#84]
HI, and thanks for this library, it made my LDAP integration really easy!

I am trying to add some functional tests in my authentication flow and I am blocked by the Bound attribute which I cannot mock because readonly.
Is there a workaround to get a `Bound = true` on a mocked authentication?

I am using the v3.0.0-beta4 and Moq for testing.
Here is the code I use to check the Bound param:
```
LdapEntry entry = results.Next();
if (entry != null)
{
    _connection.Bind(entry.Dn, password);
    if (_connection.Bound)
    {
        return entry;
    }
}
```

Thanks in advance!

**Comment by dsbenghe** [comment]
Not currently. But it can be added.

**Comment by Nonary** [comment]
You wouldn't even need to add a setter to it, simply add Bound to the interface and at that point it can be mocked, even if its get only.

**Comment by dsbenghe** [comment]
added to interface
