### ISSUE TITLE
LdapConnection lifetime

### ISSUE THREAD

**Issue by jonweaver** [dsbenghe/Novell.Directory.Ldap.NETStandard#86]
I'm using this library in a .NET Core API service used to check user access to a resource.  Depending on the state of the 'resource' this check may be performed multiple times meaning potentially 1000 requests/hr .  So, the question is would it acceptable to open a connection and leave it open for the life of the application?  Would there be a big performance problem if a new connection were created for each request?

**Comment by dsbenghe** [comment]
You should test to see if the performance is acceptable for your case by creating a connection every time before going into any kind of "optimization". The stress tests run during CI are doing around 25000 runs (and doing more than just connecting) in 30 min - running inside Travis CI free VMs.

**Comment by Naihan** [comment]
@dsbenghe  I too face the same question.
Im writing a webapi that need to serve about 5 million requests per day, if i where to open a connection upon receiving a request LDAP will be a big impact on performance,
i tried to leave the connection open as a class member and reuse it when a request arrives but after a couple of queries it seems that the connection is dropped. . (i check LdapConnection.Connected && LdapConnection.Bound )
am i doing something wrong? is that king of implementation is possible?

**Comment by dsbenghe** [comment]
If creating a connection for each request is not performant enough for you, you will need to implement some kind of resource/connection pooling.
