### ISSUE TITLE
StartTls() only seems to work in Windows (Running against Active Directory)

### ISSUE THREAD

**Issue by rilehudd** [dsbenghe/Novell.Directory.Ldap.NETStandard#88]
I couldn't find any known issues and wanted to make sure that there isn't something that I'm missing.

A test program compiled in Windows targeting .netcore 2.2 to perform a simple query sequence:
Connect, StartTls, Bind (Simple Bind), Search, and Disconnect.

When running within Windows 10, the sequence is completed successfully against our company's AD server. But when running inside an  Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic x86_64) virtual machine (same Windows host). I get a connect error throwing from StartTls().

The test project was published as a self-contained application targeting linux-x64. I believe this should contain all dependencies needed; but am curious if its possible some underlying dependency might not be met?

We are running inside a docker container, but to simplify the use case I've been running tests on the linux host directly.

Here is the test project for reference:
[LdapTest.zip](https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/files/3238007/LdapTest.zip)
[Edit] when creating a test project to demonstrate the issue accidentally selected a fork of the project in nuget.  Updated to the correct version.

**Comment by rilehudd** [comment]
I think this must be somehow tied to how the Active Directory server must be setup. 
Utilizing the Linux ldapsearch utils using both StartTls(-ZZ) and simple authentication (-x -W) results in a connection failure as well. We can close this out.. I'm not AD/Ldap expert; I'd be curious if you have an ideas on server configuration that would break on linux but work fine in Windows.

**Comment by rilehudd** [comment]
Here is the version I was using for reference.
![image](https://user-images.githubusercontent.com/51207004/58650060-906f7280-82c2-11e9-9f1d-763939ac9537.png)

**Comment by rilehudd** [comment]
Maybe I could attempt to use SASL to see if that direction might work. Is there documentation on how to use SASL with TLS?

**Comment by rilehudd** [comment]
It looks like this is the secret to allowing TLS to succesfully connect:
`
            connection.UserDefinedServerCertValidationDelegate += Connection_UserDefinedServerCertValidationDelegate;`

**Comment by rilehudd** [comment]
This should probably be outlined as the main examples shown are the insecure way to connect to LDAP.

**Comment by dsbenghe** [comment]
> It looks like this is the secret to allowing TLS to succesfully connect:
> ` connection.UserDefinedServerCertValidationDelegate += Connection_UserDefinedServerCertValidationDelegate;`

This is still a kind of workaround - as usually, this is implemented by disabling the certificate check. But, yeah, it looks that the certificate configuration was the problem.

**Comment by dsbenghe** [comment]
> This should probably be outlined as the main examples shown are the insecure way to connect to LDAP.

The tests have 3 ways of connecting to a ldap server - and could be used as a sample :)
