### ISSUE TITLE
How to read/set NT-Security-Descriptor attributes?

### ISSUE THREAD

**Issue by andiexer** [dsbenghe/Novell.Directory.Ldap.NETStandard#89]
hey folks

thanks for this awesome library. actually we have one problem to solve and we do not know hot to solve it. (i hope there's a solution, and i think there is one).

we actually try to read/set data from an ldap attribute with the syntax "nt security descriptor". does anybody know how to read this? i know it's a kind of Octet-String but i don't know how to get the propper values.

description of the attribute: https://ldapwiki.com/wiki/NT-Sec-Desc

I appreciate any help, hint or advise to finally solve this problem.

best regards from switzerland

andi

**Comment by dsbenghe** [comment]
LdapAttribute.ByteValue should be what you are looking for. 

Similar question here - https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/52

**Comment by andiexer** [comment]
Hey dsbenghe!
Thanks for your reply. I tried that as well. I converted the byte array value, but the string is still unreadable. I think i have to decode it as an ASN.1 string, but i don't get it to work.

Object-Security-Descriptor: 1.2.840.113556.1.4.907
        Encoded as an Octet-String (OID 1.3.6.1.4.1.1466.115.121.1.40)]

This is the description of the NT-Security-Descriptor. If it's a normal octet string i could just decode the byte value to a string and it works fine. but i don't get it to work how to decode the ASN1. 1.2.840.113556.1.4.907 to a readable string.

thanks for your help, appreciate it!

cheers, andi

**Comment by dsbenghe** [comment]
Isn't this just about correctly parsing/decoding the byte array? 

This may help - https://www.itinsights.org/Process-low-level-NtSecurityDescriptor/ 
This is a java library which parses NtSecurityDescriptor - https://stackoverflow.com/questions/16521790/how-can-i-access-the-ntsecuritydescriptor-with-a-normal-ldap-client

**Comment by dsbenghe** [comment]
Is this still an issue?

**Comment by dsbenghe** [comment]
Closing as no news for a while...

**Comment by gabeluci** [comment]
In case someone else comes across this: I wrote an article a while ago about how to deal with NT Security Descriptor attributes in C#. Specifically, how to get the byte array into a .NET type that you can work with.

See here: [Active Directory: Handling NT Security Descriptor attributes](https://www.gabescode.com/active-directory/2019/07/25/nt-security-descriptors.html)
