### ISSUE TITLE
Update sources based on 2013 year version

### ISSUE THREAD

**Issue by mirik123** [dsbenghe/Novell.Directory.Ldap.NETStandard#9]
The C# classes are based on 2009 year version and miss many important features.
It would be cool to have an updated C# classes based on the latest 2013 year Java sources.

https://www.novell.com/documentation/developer/jldap/jldapenu/api/
https://www.novell.com/developer/ndk/ldap_classes_for_java.html

**Comment by dsbenghe** [comment]
What exactly are the features (which you think are important) which are missing from the .net version but are in the java version (I know sasl is one of them)?

It will be nice to do it - but will require someone motivated enough (e.g. needs these new features) to spend the time to add them :) - Happy to take pull requests.

**Comment by mirik123** [comment]
Actually it is only one feature but really critical - authentication using client certificate

**Comment by dsbenghe** [comment]
Maybe you want to give it a go - at a first look should be reasonable straightforward to implement it. Authentication with client certificate is supported by SslStream. Looking at the java implementation will help  with the ldap specific bits.

**Comment by tgitchel** [comment]
I also have a critical need for this feature.  Is there anything I can do to assist?  Perhaps code review/testing?  I don't want to duplicate ongoing efforts, but happy to pitch in if it would help speed up the process.

**Comment by yobdoy** [comment]
I'm willing to help too to implement this feature

Best regards,

**Comment by se** [comment]
Did anyone work on this? I can also help to implement it if there is a sample (could be different programming languages) about it.

**Comment by dsbenghe** [comment]
Sasl authentication was implemented for a while. Sasl external with client certificate was just merged to master and it will get published with 3.6.x. Don't think it is anything left in the 2013 java version which is worth replicating.

If anyone thinks otherwise please raise your hand.
