### ISSUE TITLE
Connect fails with Error 91

### ISSUE THREAD

**Issue by DerKiLLa** [dsbenghe/Novell.Directory.Ldap.NETStandard#90]
Hi!

I've some problems with this ... using UWP and C# and try to connect to our LDAP. 

```
string ldapHost = "domain.local";
int ldapPort = 389;
LdapConnection conn = new LdapConnection();
conn.Connect(ldapHost, ldapPort);
```
Fails with: 
Cause = {"Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig xx.xx.xx.xx:389"}

I also tried port 686 and SSL ... nothing works. Same error ... Any ideas?

**Comment by dsbenghe** [comment]
This seems to be a permission issue (maybe related with UWP)

**Comment by dsbenghe** [comment]
No news for a while - issue closed. If you still have issues which you think are related to the library please reply.
