### ISSUE TITLE
A Call to SSPI failed

### ISSUE THREAD

**Issue by mubeda** [dsbenghe/Novell.Directory.Ldap.NETStandard#92]
Hello!
I created created a netstandard lib to handle my  ldap connections from .net 4.7 framework and netCore 2.0 related projects.  Basically i found this problem with projects with the first one while using SSL connections .  I tried the stable version fo the lib and the latest 3.0 beta 4, and i am still facing the problem.  So, after some research, i found  some info for a possible solution here. 
[https://github.com/dotnet/corefx/issues/23332
](https://github.com/dotnet/corefx/issues/23332)

I cloned your repository and performed  a change on the Connection.cs file , line 548 and changed the line to this

`
sslstream.AuthenticateAsClientAsync(host, null, SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12, false).WaitAndUnwrap(ConnectionTimeout);`

The error is gone, it works with both types of projects. I will use my the lib i built until a new version of  the nuget library arrives with a fix for this exception.
Tks!

**Comment by dsbenghe** [comment]
Please create a PR with this change. If not you will need to wait for me to do this change.

**Comment by dsbenghe** [comment]
Since 3.6.x new feature was introduced so the SslProtocols which can be configured e.g.

`           
var options = new LdapConnectionOptions()
    .UseSsl()
    .ConfigureSslProtocols(SslProtocols.Ssl2);
using var ldapConnection = new LdapConnection(options);
ldapConnection.Connect(...)
`
