### ISSUE TITLE
nu-get update?

### ISSUE THREAD

**Issue by barry-r-moore** [dsbenghe/Novell.Directory.Ldap.NETStandard#95]
Hi,

is it possible to issue a new release of the lib for NuGet?

Presently i can only access version 3.1.0 on NuGet, which is missing the recent changes from this commit:

https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/commit/a24a377687e79a18830efb8059eadf89c31837f6

Thanks

Barry

**Comment by dsbenghe** [comment]
https://www.nuget.org/packages/Novell.Directory.Ldap.NETStandard/3.0.0-beta5
