### ISSUE TITLE
Have GetAttribute return NULL rather than throw KeyNotFoundException when named attribute not present

### ISSUE THREAD

**Issue by PDRDaveF** [dsbenghe/Novell.Directory.Ldap.NETStandard#98]
Can I suggest either having GetAttribute return null, or have a TryGetAttribute method, when the requested attribute name isn't present?

Also, is there timeframe for when ClientCertificates will come out of prerelease?

Thanks in advance,

Dave

**Comment by dsbenghe** [comment]
IMHO returning null is not a good practice. You can check the attributes to see if exists or not before doing GetAttribute. With that you can implement your own TryGet.
