### ISSUE TITLE
Problem with "Simple paged results control" and LdapVirtualListControl for large results (>10000 entries)

### ISSUE THREAD

**Issue by Rat70** [dsbenghe/Novell.Directory.Ldap.NETStandard#99]
Hi, we are struggling with fetching more than 10000 entries from an Active Directory. 

We have tried the LdapVirtualListControl ([LdapVirtualListControl problem on stackoverflow](https://stackoverflow.com/questions/58461921/how-to-do-a-paged-search-on-an-ldap-server-with-10000-entries-using-novell-dir)). 
We are now trying with "Simple paged result control" [(Simple paged)](https://ldapwiki.com/wiki/Simple%20Paged%20Results%20Control) with no success: [Simple paged problem on stackoverflow](https://stackoverflow.com/questions/58472427/how-to-do-a-paged-search-on-an-ldap-server-using-novell-directory-ldap-netstanda). 

Have tried both 2.3.8 and 3.0.0 beta 5 with no luck, is there a problem in Novell.Directory.Ldap.NETStandard or are we doing something wrong?

**Comment by dsbenghe** [comment]
version >= 3.5.1 have SimplePagedResultsControl implemented and there are samples and helpers implemented to use SimplePagedResultsControl and VLV control for doing paged searches - see the tests for examples. 

I run a test with 50k entries with no problems - is true, while using OpenDJ and not ActiveDirectory.
